### ISSUE TITLE
Models & Collections/Scopes Need Event Dispatching 

### ISSUE THREAD

**Issue by d4tocchini** [tower-archive/tower#1]
Models need such things as a `change` event that get passed all changed model attributes.  right now, tower models are dependent on tower controllers for notification of model state.  models need to notify state, independent of controllers.  

something like:

``` coffeescript
class Car extends Tower.Model

car = new Car color:'red'

car.bind 'change', (model) ->
  changedAttrs = model.changedAttributes()
  if changedAttrs.color
    alert "Your changed color to:#{changedAttrs.color}"

car.updateAttributes color:'red'  # no alert!
car.updateAttributes color:'blue' # alert!
```

spine or backbone-like events can easily be spun in there...

**Comment by lancejpollard** [comment]
Here's the event API from `Tower.Support.EventEmitter` (similar to the [node.js eventEmitter API](http://nodejs.org/docs/v0.6.1/api/events.html)):

``` coffeescript
class App.Car extends Tower.Model

car = new App.Car(color: "red")

car.on "change", (event) ->
  event.attribute # "color"
  event.oldValue # "red"
  event.newValue # "blue"
  @changes # {color: ["red", "blue"]}

car.set "color", "blue"
```

Need to update the main branch with this feature.  But I want to be careful in adding it, because if you don't want events as a developer the code shouldn't be executing event code (dispatching events without any listeners and all that).  You may want this if you're using Knockout.js, since their "observable" and "observableArray" basically wraps a model/collection and adds event dispatching.  It might be a waste in that case to have event dispatching code built into Tower.

As for "collections", that's pretty much the same as Knockout.js' "observableArray".  Still figuring out a better collection api…  Not sure yet if there needs to be a separate "Collection" object, or if you can just have event dispatching off the `Tower.Model.Scope` object.

``` coffeescript
# new Tower.Collection(scope)
newCars = new Tower.Collection(App.Car.where(year: ">=": 2010))
```

The collection object would take the place of something like Knockout.js' observableArray, but I'm not quite sure what the use case is for this yet.

Another issue that comes up is how you're notified of an attribute change.  This is where Knockout.js really solves the problem well.  For example, you can add/remove an item to array a bunch of different ways:

``` coffeescript
tags = ["ruby"]
tags.push("javascript")
tags = tags.concat(["node.js"])
tags.splice(1, 1) # ["ruby", "node.js"]
delete tags[0] # [undefined, "node.js"]
tags.pop() # [undefined]
tags.length = 0 # []
```

In all of those cases you modified the array, but no event is going to be dispatched.  Knockout.js solves this by using the observableArray which is basically a custom array class (https://github.com/SteveSanderson/knockout/blob/master/src/subscribables/observableArray.js#L95).

So my thinking on one hand is, if you want _real_ event dispatching, use something like Knockout.js because they handle a lot more of those cases.  And rewriting that code is probably out of the scope of Tower.  But on the other hand, having events makes some things easier to do.  Still thinking…

**Comment by lancejpollard** [comment]
Side note, if you're just looking for general "event dispatching" functionality for any object, I'd check out a dedicated (and lean) library such as:
- https://github.com/hij1nx/EventEmitter2

If you want a model that has attributes that dispatch change events but that's not necessarily built around the idea of data (like Tower and other "web app" MVC frameworks), I'd just build a lean little thing for that, a `get` and `set` method with calls to `trigger` or whatever from EventEmitter2.

**Comment by lancejpollard** [comment]
Update on this feature.  Tower won't be building any sort of EventEmitter or binding functionality like Knockout.js.  There's a potential that Tower will show some demos with these types of binding frameworks and I'll make sure to make everything compatible.

There's also the potential that tower uses something like the core ember/ruby object model like we've talked about.
