### ISSUE TITLE
Autoloading doesn't appear to work (yet?)

### ISSUE THREAD

**Issue by contentfree** [tower-archive/tower#114]
I have a BaseModel that other models extend. However, any model whose name is < BaseModel causes "Could not find module" errors. For those classes I have to add `require "" + Tower.root + "/app/models/baseModel"` to the top.

**Comment by lancejpollard** [comment]
You're right, the current implementation is very primitive and needs to be made more robust.  It only reloads the changed file.

Currently, it tells you the path to the file that's been changed:

[/tower/server/application/watcher.coffee#L45](https://github.com/viatropos/tower/blob/2a532c3fd51289ecd4f27079689556212747a3e3/src/tower/server/application/watcher.coffee#L45)

``` coffeescript

Tower.Application.Watcher =
  # ...
  fileChanged: (path) ->
    # this is a tmp solution, more robust coming later.
    if path.match(/app\/views/)
      Tower.View.cache = {}
    return unless path.match(/app\/(models|controllers)/)
    path = require.resolve("#{Tower.root}/#{path}")
    delete require.cache[path]
    process.nextTick -> require(path)
```

We should just make this method more robust.  It should also be able to handle customization, so if you have some edge case or special way of organizing your code, you should be able to make the reload work.

In order to do that, we need a more robust way of tracking the class hierarchies and module inclusions.  Ember shines at this, so we should have this soon, and might work along these lines:

``` coffeescript
klass = Tower.pathToConstant(path)
    for subklass in klass.subclasses
      require(Tower.constantToPath(subklass))
    for mixin in klass.mixins
      require(Tower.constantToPath(mixin))
```

I'd rather avoid the nodemon solution of restarting the server every time a file is changed.

Won't be able to get to this for a little while.

**Comment by contentfree** [comment]
I'm not following, I'm not talking about reloading files (though that will be useful). I'm talking about autoloading dependencies. Given:

```
# app/models/baseModel.coffee
class App.BaseModel extends Tower.Model
  # stuff

# app/models/address.coffee
class App.Address extends App.BaseModel
  # Throws an error because App.BaseModel is not loaded yet and doesn't autoload when not found.
```

Probably needs a try/catch block that will catch the Module Not Found errors and look in the autoload paths for the Thing.

**Comment by contentfree** [comment]
To make `App.Address` work in this case I have to prepend `require "#{Tower.root}/app/models/baseModel"` to it.

**Comment by lancejpollard** [comment]
Oh right.  I think the try/catch solution doesn't work across all browsers (it's basically `method_missing`).  For now you have to manually require it like you're saying.
