### ISSUE TITLE
Routes @resource defaults

### ISSUE THREAD

**Issue by Akkuma** [tower-archive/tower#125]
I currently have `@resource 'users'` in my Routes the problem is that in my `usersController` all actions are commented out. Perhaps it is just me, but it seems like if I don't explicitly have anything defined, no actions should be occurring. This could open up a huge security hole from my perspective.

**Comment by lancejpollard** [comment]
This was intended. There just needs to be a way to opt-out of (or perhaps opt-in to) using "resourceful controllers".  It's borrowed from https://github.com/josevalim/inherited_resources.

All of the actions are implemented by default.  If you comment out the route and manually place the routes you want, that's one way to avoid the security hole of potential unwanted actions.  Another approach would be to have a class method that disables/enables default actions:

``` coffeescript
class App.PostsControllers extends App.Controller
  @resourceful()
```

We'll have to think about what we all prefer.  I personally want to have the controller actions implemented by default because they should be exactly the same 90% of the time (fat models, skinny controllers).  But this does mean the app developer would have to take responsibility for making sure no security holes are present (want to minimize this burden as well).

Also, you can use `only` and `except` to filter actions.
