### ISSUE TITLE
Discussion: Ignore generated JS files in .gitignore

### ISSUE THREAD

**Issue by sebastianhoitz** [tower-archive/tower#130]
I want to discuss whether it would make sense to add the JS files in lib to the .gitignore file.

We have a separate build for npm, anyways. And all the JS files just fill up the diff screen here on github.
Especially with the many different ways coffeescript can compile the JS files:

no wrapping function / wrapping function / version comment at the beginning of the file, ...

The advantages are:
- easier to understand the commit diffs
- faster navigation / access
- no different generated JS formats

Disadvantages might be:
- Developer has to know, that he has to compile the JS files first.
  But I think this should be fairly easy to explain to developers.

@viatropos Can you please label this as discussion? It seems I can't assign labels.

**Comment by lancejpollard** [comment]
Agreed, we should do this.

It's also particularly annoying that some commits that were accepted (and lots of my own) say 15,000 additions, 14,000 deletions.  Is there a way to permanently remove everything in the `lib` folder from git history, such that it 1) doesn't cause any problems such as with people who've already forked the project, and 2) that it also updates the [commit graphs](https://github.com/viatropos/tower/graphs/contributors) (do you know if @GitHub is reading this dynamically or is it permanently there in history no matter if we hard-remove it from the git history?).  If you know how to do this let me know, I've always avoided changing git history in the past b/c it did strange things, but this is a case where we should do it.

Another thing we need to do to make this happen: move the generator templates to `src`, which will require some more sophisticated compiling steps.  Or we can leave it in lib, just need to think about this as well.

The last thing is we'll have to go through a thorough testing phase on different operating systems and such to make sure coffee-script compilation works as expected (since you have to compile it on the spot).

Love how you described the advantages and disadvantages, that's the kind of stuff we need to make good decisions.

**Comment by lancejpollard** [comment]
One solution is to run a post-install hook to generate `lib` javascripts when you do `npm install`.  I imagine we may run into conflicts if someone does `npm install coffee-script` inside a project directory after installing tower, then tower will use that version, which may not be compatible.

By precompiling like this, technically you wouldn't even need coffee-script, and could write your whole app in JavaScript.

**Comment by sebastianhoitz** [comment]
There is some information here on how to remove a folder from history: http://progit.org/book/ch9-7.html But I don't know if/how this works on Github.

We have our own coffee-script as a dependency, right?
We could just hard-wire it to that binary. So when npm installing tower, we could do something like this:

```
./node_modules/coffee-script/bin/coffee -b -o lib -c src
```

where the coffee-script is our custom coffee-script.

**Comment by sebastianhoitz** [comment]
Another possiblity would be to just use the .coffee files and execute the server using coffee.

This way we wouldn't have to generate the JS files at all. What do you think about this? This would mean, though, that you can't easily use tower without CoffeeScript. Then you would have to generate the JS files.

**Comment by lancejpollard** [comment]
This is happening in the dev branch now.
