### ISSUE TITLE
mongodb without callback

### ISSUE THREAD

**Issue by avastou** [tower-archive/tower#150]
I've made ​​a mistake?

``` coffee
        user  = App.User.first()
        console.log user
        #return undefined
```

The method without callback does not work with mongodb store...

**Comment by lancejpollard** [comment]
Yeah won't work because the mongo store is asynchronous so it requires a callback.  In the next version of Tower we're pushing out here soon all finder methods that return an array will return a blank array if it's asynchronous, but that same array will be populated with the records once they arrive.  This way you can do `users = App.User.all()` in the console and an instant later check the value of `users` and it will contain the records.   For `first`, `last`, and `find(id)`, it will return undefined in async stores.
