### ISSUE TITLE
Consolidate Documentation

### ISSUE THREAD

**Issue by Akkuma** [tower-archive/tower#158]
Currently there is documentation all over the place the ReadMe, the wiki, and towerjs.org. It seems to me one or more of these should be removed to reduce confusion. My recommendation is to either move the documentation all to towerjs.org or all into the wiki depending on whether you want collaboration to occur. Probably the best bet would be to turn towerjs.org into a quick rundown of what Tower offers as a sort of better organized and ehanced ReadMe, since wikis tend to work really well for documentation.

**Comment by lancejpollard** [comment]
I'm torn on this one. Most projects have the documentation on their website (ember, rails, jquery for example). A few have it on the wiki (homebrew, d3.js). But people are able to contribute to projects like rails' docs, so contribution is not affected by whether or not it's using a wiki.

I think we should probably just remove the wiki and put the wiki content into a separate repo, like `tower-docs` (similar to https://github.com/lifo/docrails). The main issue is that google indexes the content in the wiki but _not_ in the repo. If there was some way to prevent google from indexing the wiki that might make it less confusing. But I get what you're saying, it's confusing now. The docs are incomplete and changing fast right now because of all the development going on. I'm going to refactor the docs soon.

**Comment by edubkendo** [comment]
+1 keeping a second set in a "tower docs" repo.
I really like the idea of having two sets of docs, a semi-permanent, _this stuff works_, very unlikely to change much set of documentation on the towerjs website, and an easy to add-to, alter, etc set that is kind of in flux, and easy for anyone in the community to build on. Of course as development slows down, new features become less common, etc, having the second set may be less useful, but for now I personally like it very much. I think it encourages community contributions when they can see the effects right away, etc. At the same time, having a set of less mutable docs that I know have been vetted and 'finalized' is awesome. I think moving the docs that are in the wiki now into a separate repo so they dont get indexed is a great idea. Also, eagerly looking forward to your refactoring of the docs and all the other cool stuff coming soon.
