### ISSUE TITLE
hasMany accessor. Get the child's parent return all avalaible 'parents'

### ISSUE THREAD

**Issue by marcinrogacki** [tower-archive/tower#161]
I made a simple test. I added a few user and posts associated with each of them.
e.g. App.User.count = 5, App.Post.count = 50 (5users x 10posts)

When I want get all posts of user, I'll do:

```
App.User.where(email: "some@email.com").first (err, user) =>
  user.posts().count (err, count) =>
    console.log count # => 10 
```

So it working, but when I try get an user of current post I get all users from database

```
    App.Post.where(id: "4fd896a101b77d172a000003").first (err, post) =>
      post.user().count (err, count) =>
        console.log  count # => 5
```

**Comment by edubkendo** [comment]
Maybe a really obvious question, but did you set up belongsTo on the post model or just hasMany on the user?

**Comment by marcinrogacki** [comment]
Yes, I do. Oh, I forgot about ur demo API. Tomorrow I'll check it. If it still fails, I'll push some my demo :)
greets

**Comment by marcinrogacki** [comment]
Ok, it does not work. I forked your app demo and I added displaying post owner(s)
https://github.com/robak1987/demoApp.git

Codes of getting parent of post:

```
@post.user().all (error, @users) => # fetchs all users in db
@post.user().first (error, @user) => # fetchs first user of all users in db
@post.user().last (error, @user) => # to more funny it fetch also FIRST user of all users in db :)
```

**Comment by edubkendo** [comment]
Yup, did a bunch of experiments myself trying to make this work and I agree it's not reciprocal.  Anything you try involving post.user() comes back very different from what you would expect.

**Comment by edubkendo** [comment]
Temporary workaround, if you haven't worked this one out for yourself, is something like:

``` coffeescript
  show:  ->
    App.Post.find @params.id, (error, @post) =>
      if @post
        @user = {}
        @post.user().where(id: @post.attributes.userId).all (error, @user) =>
          console.log @user
          @render "show"
      else
        @redirectTo "index"
```

Meanwhile, taking a look into the root problem here, if @viatropos doesn't get to it first.

**Comment by edubkendo** [comment]
@viatropos Ok. Best I can tell, the problem seems to be in the BelongsTo.Criteria subclass, and specifically with the pseudo-constructor ToCriteria method. If it worked right, it is what would work to narrow down the scope to return the specific record(s) that the owner record belongs to.  

As far as I can tell, however, this ToCriteria method never gets called from anywhere in the codebase, nor run in any other way, so the scope on a BelongsTo query ends up being the generic Criteria, in other words, wide open. I may be wrong, as this has been the most complex part of Tower I've attempted to wrap my whole head around at once yet.  

Nothing I've tried doing to fix the error (such as attempts to turn ToCriteria into "constructor" and some other attemots), but i will look into it some more Monday if it isnt figured out by then.

**Comment by marcinrogacki** [comment]
Yes, also I did this workaround. Maybe just this feature is not yet refactored (so how you got the answer here [Stackoverflow on-to-many](http://stackoverflow.com/questions/10749758/how-do-i-use-one-to-many-relationships-in-tower-js). Anyway I posted issue to others. Thanks for support :)

**Comment by lancejpollard** [comment]
Working on a much more robust solution to this.
