### ISSUE TITLE
interpolation of I18n string fails

### ISSUE THREAD

**Issue by scottkf** [tower-archive/tower#169]
https://github.com/viatropos/tower/blob/master/src/tower/view/helpers/stringHelper.coffee#L17

Not passing an optional hash causes interpolation to fail

**Comment by lancejpollard** [comment]
Thanks!

**Comment by scottkf** [comment]
As a side note, thanks for towerjs! I'll probably stick with towerjs for a while (I need to move a high performance sites to node, and I don't want  to reinvent the wheel), and will have quite a few more things. I'd be happy to submit pull requests and tests, do you have any guidelines for pull requests?

**Comment by lancejpollard** [comment]
Awesome. Yeah, there's a lot to do still, feel free to send pull requests whenever. I'm working purely in the development branch now and won't really mess with master until the model layer in dev is working well, which might take a couple more weeks. If you create pull requests for master, I'll merge them in when I merge dev back to master because you're finding things that I haven't noticed in master or dev :) thanks! Since the code base is growing so fast I'm not too rigid about writing lots of tests, but if you do all the better. As the project stabilizes though tests will be key. That's it for now, looking forward to your contributions.

**Comment by krainboltgreene** [comment]
Ok, so I'm going to chime in here because I've had a bone to pick with i18n done the Rails way (see here: https://gist.github.com/2866752#gistcomment-342072). This might be a good chance to make a pull request and see my vision in Tower.js.
