### ISSUE TITLE
MongoDB adapter: is createdAt really needed?

### ISSUE THREAD

**Issue by scottkf** [tower-archive/tower#173]
Since you're using an ObjectID as the id for an entry, you can extract the time createdAt from the ObjectID with the node module: using `objectId.getTimestamp()`

http://www.mongodb.org/display/DOCS/Optimizing+Object+IDs#OptimizingObjectIDs-Extractinsertiontimesfromidratherthanhavingaseparatetimestampfield.

Do you have change the date an item was created, other than in testing?

**Comment by lancejpollard** [comment]
That's cool, didn't realize that was there. The major reason you'd want the actual `createdAt` field is to be able to query over it:

``` coffeescript
App.User.where(createdAt: '>=': _(2).days().ago().toDate()).all()
```

If there wasn't a field like that, we'd have to create a special adapter to convert `createdAt` into some query function for the id, which I don't even know is possible (or optimal). If it is possible to query the date from within the id let me know, otherwise it's too much a performance hit for this optimization. Closing the issue for now.

You would use this optimization for things like metrics though, will be implementing something like this after 0.5.0: http://engineering.foursquare.com/2011/02/09/mongodb-strategies-for-the-disk-averse/
