### ISSUE TITLE
index.js is strange?

### ISSUE THREAD

**Issue by krainboltgreene** [tower-archive/tower#185]
While going through tower.js I found this `index.js` file in the root:

``` javascript
var path = require('path');
require('coffee-script');
if (path.existsSync('./lib/tower.js'))
  module.exports = require('./lib/tower.js');
else
  module.exports = require('./src/tower.coffee');
```

There is no './lib/tower.js', and that's not a valid if statement in js I think.

**Comment by lancejpollard** [comment]
This is a tmp hack to make debugging easier in development. It's a valid if statement (for one-liners you don't need curly brackets if that's what you mean). If './lib/tower.js' exists (it will if you've compiled tower with design.io), then it'll use the javascript files, otherwise the coffeescript.

In the end, I think it should be such that the NPM version only gets the JavaScript version, but in development you should be able to do both.
