### ISSUE TITLE
Can't reset a Hash attribute in a model

### ISSUE THREAD

**Issue by scottkf** [tower-archive/tower#190]
``` coffeescript
class App.Test extends Tower.Model
  @field 'u', type: 'Hash', default: {}

t = new App.Test()
t.set 'u', example: true
t.save
t.reload
t.get 'u' # {example: true}
to.set 'u', {}
t.save
t.reload
t.get 'u', # {example: true}
```

This happens because of either the dirtyAttributes or changedAttributes in https://github.com/viatropos/tower/blob/development/src/tower/model/dirty.coffee#L34-39 . It might be related to ember, I stopped tracing it back once it got here

**Comment by lancejpollard** [comment]
Nice one. This is the main/big thing I'm working on right now, making the dirty attributes functionality much better. There's a few things that seem to be off, and I want to get rid of that Tower.Model.Data object. Hoping to finish refactoring/fixing this stuff in the next few days. Any help would be awesome, let me know.

**Comment by lancejpollard** [comment]
Also, reload is a method (in case the above isn't pseudocode), so it should be `t.reload()`.

**Comment by scottkf** [comment]
It was just pseudocode, in order to get what I was working on working, I just used an Integer with bitwise operations instead of a Hash, but I'll keep digging tomorrow and write some tests

**Comment by lancejpollard** [comment]
FYI, the issue is kind of complicated. Here's a couple of things.

First, the new api isn't going to use `new App.User`, because Ember doesn't allow this (I asked if they could change but they basically said no). To construct a new `Ember.Object` they use `Ember.Object.create()`, but since `create` on a model is for saving it to the database as well, Tower is using `build`:

``` coffeescript
user = App.User.build(email: 'example@gmail.com')
```

The issue with `new App.User(props)` is that the mixins in Ember don't get applied.

Then for the `dirtyAttributes`... There are two ways models need to be constructed:
1. Manually, where the developer writes `App.User.build(props)`
2. Internally, when you serialize a database record to a model. This (is going to) have the API `App.User.build(props, isNew: false)`. Rails does this as well but it's not very clean/well documented.

The reason for this is b/c it changes the way attribute changes are tracked (since initial attributes are different). Right now, the issue is that, while Tower is handling serializing the already-saved attributes properly (so they don't act as changed values), it doesn't track the changes "properly" in some cases (this is what I'm figuring out/solving now).
