### ISSUE TITLE
Discussion: PJAX

### ISSUE THREAD

**Issue by maedi** [tower-archive/tower#237]
Curious to hear your thoughts on PJAX. 37Signals recently used it to speed up their Basecamp Rails app, allowing them to continue using server side code rather than client (Ember).

Basecamp Article:
http://37signals.com/svn/posts/3112-how-basecamp-next-got-to-be-so-damn-fast-without-using-much-client-side-ui

Node integration:
http://blog.ntotten.com/2012/04/09/building-super-fast-web-apps-with-pjax/
http://toolbox.no.de/packages/express-pjax

**Comment by autoferrit** [comment]
Great article, having support for something like that would be great. Makes me think a lot about how here at work were using json so much to transfer data, and whether or not we should do it differently

**Comment by lancejpollard** [comment]
Will get back to you soon with a detailed response.

**Comment by lancejpollard** [comment]
Posting some links here (for perspective):
- http://ninjasandrobots.com/html5-page-cache-with-pjax-localstorage-firebase
- http://stackoverflow.com/questions/9237069/do-i-really-need-an-mvc-framework-like-backbone-js-or-ember-js-in-rails-for-a-si
- http://asciicasts.com/episodes/294-playing-with-pjax
- https://github.com/emberjs/ember.js/issues/161
- http://cantina.co/2012/06/04/a-faster-web-with-pjax/
- http://engineering.twitter.com/2012/05/improving-performance-on-twittercom.html

Twitter and GitHub also use a kind of PJAX approach (twitter after trying client-side architecture).

Pros of PJAX:
- Less javascript to download on the client (potentially much less). But this is only a performance problem on first page load or a forced refresh (which does happen often).
- Better performance on mobile devices (since most browsers today can handle 500kb+ rich javascript apps just fine, but mobile struggles a little, with things like template rendering).
- More optimized HTTP requests, since you get back pre-processed HTML that can be inserted into the DOM without any processing.

Cons of PJAX:

[coming]

**Comment by maedi** [comment]
From the Twitter article:
"In our fully client-side architecture, you don’t see anything until our JavaScript is downloaded and executed [...] The bottom line is that a client-side architecture leads to slower performance because most of the code is being executed on our users' machines rather than our own. [...] We took the execution of JavaScript completely out of our render path. By rendering our page content on the server and deferring all JavaScript execution until well after that content has been rendered, we've dropped the time to first Tweet to one-fifth of what it was."

Is this what we currently have with Ember? Is there a way to render the initial variables on the server for the first page render? I think Twitter are correct in saying that JS affects the first page load, but surely JSON over the wire for every secondary page is the fastest? Or is the "downloading + processing" time slower than downloading HTML?

**Comment by d4tocchini** [comment]
@Maedi, your questions hit the nail on the head.  Yes, server-side rendering is faster for initial load.  And, yes, JSON over the network for views created asyncly from user generated data is faster then sending the JSON to the server and then waiting for the server to respond with HTML.  

The problem with the old Twitter client-side architecture was that it was "fully" client-side.  The ideal situation is to have both client-side and server-side view rendering via Javascript.  Tower is pure js that lives in the browser and node, it thus has a unique ability to render views everywhere.  Ideally a Tower app could optimize itself by using server-side or client-side depending on the circumstances.

[Here's a talk from the guys at Yahoo (Douglas Crockford peeps) that explains this ideal situation](http://www.youtube.com/watch?v=sGpHDHAIpYE)

[A presentation on "Views Anywhere"](http://www.slideshare.net/sylvinus/node-camp)

Basically, the benefits of pure a JavaScript framework that runs on the client and server renders this a non-issue because it unifies view rendering infrastructures.  This is why the guys at Rails probably should stick with server-side view rendering, otherwise they would have to begin building an entirely new infrastructure like Ember in the browser.  Likewise, Ember is pure client-side (at least for now), so it's more optimized for _ambitious_ single page applications where there is only a single "initial-load" to be concerned with.  The question shouldn't be server-side or client-side view rendering, it should be: how can we have both & and when should we use one over the other?  Tower is in a unique postion to offer both and bake in conventions that use the right one for the right circumstance...

**Comment by lancejpollard** [comment]
> but surely JSON over the wire for every secondary page is the fastest? Or is the "downloading + processing" time slower than downloading HTML?

@Maedi We need to benchmark this. I suspect that it's probably about the same for laptop/desktop browsers, but that it's much faster to send HTML from the sever (instead of JSON) for mobile devices. The thing to note is, on the server, you can cache the generated HTML and JSON for a particular request, so assuming you have done that, rendering is basically "instant" no matter if you ask for HTML or JSON. So this creates two sub-questions:
1. What is the size difference between the server's HTML and JSON responses for a particular request, and are these size differences significant? I imagine the HTML response can easily be twice as large as the JSON response (one thing to test), but that this doesn't add any significant time to the response (assuming everything is cached in memcached/redis, then if the response is 200kb vs. 100kb, that is only going to add a couple milliseconds to the response time - another thing to test).
2. How long does it take to insert server-generated HTML into the DOM vs. compile the JSON into HTML then insert it into the DOM all on the client? I suspect there is no _noticeable_ performance impact for simple HTML structures (simple lists/tables/etc.) _on laptop/desktop browsers_ (something to test), but I suspect there to be a noticeable performance hit for even simple lists on mobile browsers (something to test), and a noticeable performance hit for more complex ui elements on laptop/desktop browsers (though this one is hard to test because you don't run into complex ui elements that often, at least I can't think of any).

@d4tocchini We should definitely try to integrate both methods of rendering (client and server), and have Tower be intelligent enough to figure out when to use each. I like what you're saying there, will checkout that video. The main difficulty at this point is, if you have the server render the initial page (static HTML, the way twitter is doing it), I don't know how to get ember to then "backtrack" and convert that into an "ember view" (which you can do with knockout b/c they read the `data-bind` tags). Ember forces you to put the "templates" into `<script>` blocks, but to get the performance boost from the server generated HTML, you don't want to wrap it in script tags. The question is, if you did that, how do you get Ember to make those views? If we could figure that out then we'd be golden.

**Comment by d4tocchini** [comment]
You're right @viatropos - the missing piece is how do we get server-rendered views to hook-up to Ember runtime?  ...  I know Ember-Data does something similar with Rails...

I think [Yehuda's tweet](https://twitter.com/wycats/status/178255680623480833) sums up 37 signals perspective: 

> "@BrendanEich You missed the joke ;) 37Signals thinks JS is so hard that they're doing caching instead (see https://37signals.com/svn/posts/3112-how-basecamp-next-got-to-be-so-damn-fast-without-using-much-client-side-ui …)"

That video from the Yahoo team explains that bootstrapping JSON and pushing _all_ the views to the client for rendering is ideal in the unique circumstance when the entire app is a single page that is comprised of many smaller encapsulated elements, ie. MyYahoo.  Douglas Crockford supports this perspective in the [Crockford on JavaScript Lectures](http://yuiblog.com/crockford/), i think he mentions this on the last lecture...

If you're building a more synchronous App with many initial page loads, server-side view rendering would help for sure, but you would still need the client-side templates in order for the views to reflect changes to the data.

[Yehuda's 2010 announcement of handlebars](http://yehudakatz.com/2010/09/09/announcing-handlebars-js/) touches on some of these issues:

> "I have been active in server-side development (through Merb and then Rails). Recently, I’ve released a couple of libraries (jQuery Offline and Rack::Offline), designed to make it easier to build applications that can withstand both flaky connections and a complete lack of connectivity. Of course, those libraries leveraged features in modern browsers, and have gotten a bunch of use.
> 
> For jQuery Offline, the basic strategy is that instead of requesting a new JSON object before you can show anything on the page, you first try to retrieve that data from cache, show some stale content. In parallel, you’d download the new content (if possible), and update the display with the content in question. You’ve probably seen this pattern at work in applications like the official Twitter application for the iPhone, which shows stale content when you first boot the app, and downloads new content if you have Internet connectivity in the background...."

[The guy behind mustache had a great write-up on the future of Mustache](http://writing.jan.io/mustache-2.0.html) where he talks about the trade-offs of an _ideal_ template system and ease-of-use.  His sentiment: 

> “By the time the browser has downloaded, parsed and compiled your smart compiler, my dumb parser is done rendering the template.”

hahaha
