### ISSUE TITLE
Customizing Ember's enter state to load data

### ISSUE THREAD

**Issue by scottkf** [tower-archive/tower#238]
So you wouldn't have to bootstrap all the data up front, but you could specify something like @enter: -> App.Ownership.fetch(). Not really sure how to do it, but I can see it being useful

**Comment by lancejpollard** [comment]
That's a good/interesting idea, haven't thought about that really. Will think about this more over time. It's all open ground.

**Comment by DominikGuzei** [comment]
Does this mean that there is currently no way of requesting additional data form the client-side?

**Comment by lancejpollard** [comment]
No you can request additional data, just do:

``` javascript
App.Post.where('active', true).fetch();
```

That will fetch matching records from the server. You can call that anywhere on the client, I think this issue was just asking if there was event built into ember or the controller or something like that, which you could then use as a hook to make a request like above. Going to close this, thanks for pointing out.
