### ISSUE TITLE
Install issues (a fresh CentOS 6.x install)

### ISSUE THREAD

**Issue by SwarmShepherd** [tower-archive/tower#272]
With git installed (thank you e_dub on IRC) the  

```
 npm install tower -g   
```

command went much farther :)   -  but failed first then at this point:

npm install git://github.com/viatropos/coffeecup.git --force && npm install git://github.com/viatropos/coffee-script.git --force

...doing EA of these commands alone directly into the CLI was successful  ( whatever that should mean)

Here's the related output:

System Linux 2.6.18-274.7.1.el5.028stab095.1
npm ERR! command "nodejs" "/usr/bin/npm" "install" "-g" "tower"
npm ERR! cwd /home/tower
npm ERR! node -v v0.6.18
npm ERR! npm -v 1.1.19
npm ERR! code ELIFECYCLE
npm ERR! message tower@0.4.1 postinstall: `npm install git://github.com/viatropos/coffeecup.git --force && npm install git://github.com/viatropos/coffee-script.git --force`
npm ERR! message `sh "-c" "npm install git://github.com/viatropos/coffeecup.git --force && npm install git://github.com/viatropos/coffee-script.git --force"` failed with 1
npm ERR! errno {}

Perhaps this will provide a clue?   --- note 'node path not found' ?

node-waf configure build
Setting srcdir to                        : /usr/lib/nodejs/tower/node_modules/socket.io/node_modules/redis/node_modules/hiredis 
Setting blddir to                        : /usr/lib/nodejs/tower/node_modules/socket.io/node_modules/redis/node_modules/hiredis/build 
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /usr 
'configure' finished successfully (0.030s)

Finally, this is the last output from the terminal:

> tower@0.4.1 postinstall /usr/lib/node_modules/tower
> npm install git://github.com/viatropos/coffeecup.git --force && npm install git://github.com/viatropos/coffee-script.git --force

npm ERR! Error: EACCES, open '/root/.npm/coffeecup/0.3.11/package.tgz'
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
npm ERR! 
npm ERR! System Linux 2.6.18-274.7.1.el5.028stab095.1
npm ERR! command "nodejs" "/usr/bin/npm" "install" "git://github.com/viatropos/coffeecup.git" "--force"
npm ERR! cwd /usr/lib/nodejs/tower
npm ERR! node -v v0.6.18
npm ERR! npm -v 1.1.19
npm ERR! path /root/.npm/coffeecup/0.3.11/package.tgz
npm ERR! code EACCES
npm ERR! message EACCES, open '/root/.npm/coffeecup/0.3.11/package.tgz'
npm ERR! errno {}
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /usr/lib/nodejs/tower/npm-debug.log
npm not ok

npm ERR! tower@0.4.1 postinstall: `npm install git://github.com/viatropos/coffeecup.git --force && npm install git://github.com/viatropos/coffee-script.git --force`
npm ERR! `sh "-c" "npm install git://github.com/viatropos/coffeecup.git --force && npm install git://github.com/viatropos/coffee-script.git --force"` failed with 1
npm ERR! 
npm ERR! Failed at the tower@0.4.1 postinstall script.
npm ERR! This is most likely a problem with the tower package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install git://github.com/viatropos/coffeecup.git --force && npm install git://github.com/viatropos/coffee-script.git --force
npm ERR! You can get their info via:
npm ERR!     npm owner ls tower
npm ERR! There is likely additional logging output above.
npm ERR! 
npm ERR! System Linux 2.6.18-274.7.1.el5.028stab095.1
npm ERR! command "nodejs" "/usr/bin/npm" "install" "tower" "-g"
npm ERR! cwd /home/tower
npm ERR! node -v v0.6.18
npm ERR! npm -v 1.1.19
npm ERR! code ELIFECYCLE
npm ERR! message tower@0.4.1 postinstall: `npm install git://github.com/viatropos/coffeecup.git --force && npm install git://github.com/viatropos/coffee-script.git --force`
npm ERR! message `sh "-c" "npm install git://github.com/viatropos/coffeecup.git --force && npm install git://github.com/viatropos/coffee-script.git --force"` failed with 1
npm ERR! errno {}
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/tower/npm-debug.log
npm not ok

So I'm hung up tonight and will go back to my basic Express App but the thought of "All CS all the Time is starting to really feel right for me!

Thanks!!

SwarmShepherd

**Comment by ghost** [comment]
same on Mac OS X

```

npm ERR! Error: EACCES, open '/Users/gregor/.npm/e18f6569-thub-com-viatropos-coffeecup-git.lock'
npm ERR!  { [Error: EACCES, open '/Users/gregor/.npm/e18f6569-thub-com-viatropos-coffeecup-git.lock']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/Users/gregor/.npm/e18f6569-thub-com-viatropos-coffeecup-git.lock' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Darwin 11.4.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "git://github.com/viatropos/coffeecup.git" "--force"
npm ERR! cwd /usr/local/lib/node_modules/tower
npm ERR! node -v v0.8.8
npm ERR! npm -v 1.1.59
npm ERR! path /Users/gregor/.npm/e18f6569-thub-com-viatropos-coffeecup-git.lock
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, open '/Users/gregor/.npm/e18f6569-thub-com-viatropos-coffeecup-git.lock'
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /usr/local/lib/node_modules/tower/npm-debug.log
npm ERR! not ok code 0
npm ERR! tower@0.4.1 postinstall: `npm install git://github.com/viatropos/coffeecup.git --force && npm install git://github.com/viatropos/coffee-script.git --force`
npm ERR! `sh "-c" "npm install git://github.com/viatropos/coffeecup.git --force && npm install git://github.com/viatropos/coffee-script.git --force"` failed with 3
npm ERR! 
npm ERR! Failed at the tower@0.4.1 postinstall script.
npm ERR! This is most likely a problem with the tower package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install git://github.com/viatropos/coffeecup.git --force && npm install git://github.com/viatropos/coffee-script.git --force
npm ERR! You can get their info via:
npm ERR!     npm owner ls tower
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 11.4.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "tower"
npm ERR! cwd /Users/gregor/projects/netbreeze/summary
npm ERR! node -v v0.8.8
npm ERR! npm -v 1.1.59
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/gregor/projects/netbreeze/summary/npm-debug.log
npm ERR! not ok code 0
```

**Comment by edubkendo** [comment]
@g-elke-wowbiz on MacOS check out this , I think this could be part of the problem. Note there is a 3 part solution: https://github.com/isaacs/npm/issues/2792

**Comment by j-mcnally** [comment]
Are you running npm as root? are u using sudo? the EACCESS in the log points to this being part of the issue?

**Comment by ghost** [comment]
@edubkendo i tried with a bash in root mode, but its still failing. i'm not sure why is it failing then.

@j-mcnally not sure about your questions direction. my call was with sudo (su is not working on mac os)

**Comment by j-mcnally** [comment]
the issue seems to be with git not tower actually, how did you install git?

**Comment by j-mcnally** [comment]
i would try `brew install git`

**Comment by lancejpollard** [comment]
So this was just a git issue? If so I'll close it.

**Comment by ghost** [comment]
@viatropos not for me. i have git installed, its definitly not that, as you can see in the error message:

```
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
```

there is not a "cant find command git"

**Comment by ghost** [comment]
@j-mcnally it's a preinstalled. git version 1.7.7.5 (Apple Git-26)

**Comment by edubkendo** [comment]
@g-elke-wowbiz was your first attempt with `sudo` ? Also, have you tried cleaning your cache ( `npm cache clean` ) between attempts? Try installing as root, after cleaning your cache, and using sudo, if you haven't yet. You could also try installing tower locally instead of globally just to see if it works. Finally, you could try installing from source, and then doing `npm link` afterwards. I have instructions for that in this post: http://nodehed.com/?p=69 . If you install from source, when you get to the `npm install` step, if it fails, clean your cache, then try running these seperately:

```
npm install git://github.com/viatropos/coffeecup.git --force
```

and:

```
npm install git://github.com/viatropos/coffee-script.git --force
```

If those go, go into the package.json and remove the postinstall hook (remember, this is only IF an initial attempt at npm install fails) and then run `npm install` . Then just continue with `make watch` and `npm link`. Dunno if this will work, just trying to work around whatever is going on here.

Oh, another question, what version of node do you have installed? Today I read a post on stackoverflow today where the problem the person had ended up being that it wouldn't install on 0.8.7 but would on 0.8.8.  

Anyways, just tossing some thing out there, let us know what does or doesn't end up working.

**Comment by lancejpollard** [comment]
As a sidenote, I think we should get rid of the custom coffeescript. All we really need is the ability to have the instance/class methods added as ember mixins. https://gist.github.com/3709713.

**Comment by edubkendo** [comment]
@viatropos I completely agree. That will reduce our dependencies, and it seems to be the main place where people are having issues in installation.

**Comment by ghost** [comment]
@viatropos @edubkendo i aggree. you definitly should get rid of custom deps. i'm wondering why you postinstall them via a call to npm instead of just place it in the package.json

for me, personally, i judge a tool already on installing. if it fails, or need to do more than just one or two simple calls, it big minus. may be it's too hard, but thats my philosophy about software, you should never have to fight it.

**Comment by lancejpollard** [comment]
@g-elke-wowbiz @SwarmShepherd try it now, npm now has 0.4.2-pre:

```
npm install tower -g
```

**Comment by ghost** [comment]
@viatropos another fail:

```

npm ERR! Error: EACCES, open '/Users/gregor/.npm/bcdf6e5f-ejs.lock'
npm ERR!  { [Error: EACCES, open '/Users/gregor/.npm/bcdf6e5f-ejs.lock']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/Users/gregor/.npm/bcdf6e5f-ejs.lock' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Darwin 11.4.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "ejs"
npm ERR! cwd /usr/local/lib/node_modules/tower
npm ERR! node -v v0.8.9
npm ERR! npm -v 1.1.61
npm ERR! path /Users/gregor/.npm/bcdf6e5f-ejs.lock
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, open '/Users/gregor/.npm/bcdf6e5f-ejs.lock'
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /usr/local/lib/node_modules/tower/npm-debug.log
npm ERR! not ok code 0
npm ERR! tower@0.4.2-pree postinstall: `$(./bin/dependencies)`
npm ERR! `sh "-c" "$(./bin/dependencies)"` failed with 3
npm ERR! 
npm ERR! Failed at the tower@0.4.2-pree postinstall script.
npm ERR! This is most likely a problem with the tower package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     $(./bin/dependencies)
npm ERR! You can get their info via:
npm ERR!     npm owner ls tower
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 11.4.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "tower" "-g"
npm ERR! cwd /Users/gregor/projects/netbreeze/summary/TopicSummary
npm ERR! node -v v0.8.9
npm ERR! npm -v 1.1.61
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/gregor/projects/netbreeze/summary/TopicSummary/npm-debug.log
npm ERR! not ok code 0
```

**Comment by lancejpollard** [comment]
Did you install node with homebrew? It's some permissions error. Maybe it's a node 0.8.9 error, I'm on node 0.8.2. Hmm...

Maybe the new OS doesn't allow piping commands like `$(./bin/dependencies)`?

**Comment by lancejpollard** [comment]
Try it now, removed all custom `--global` postinstall scripts (0.4.2-1).

**Comment by ghost** [comment]
@viatropos i installed node via macos installer
0.4.2-1 installation worked

dunno about piping in osx :)

**Comment by lancejpollard** [comment]
Ah that's probably it then. Not sure exactly but homebrew installs everything without root permissions I think, but the node installer may have asked to enter your password at some point, which would mean there's some protected paths. Wonder what happens if you do:

```
sudo npm install tower@0.4.2-pree -g
```

If you can install node with Homebrew I would do that if I were you, it will make installing other things later much easier.

Glad 0.4.2 is working!

**Comment by ghost** [comment]
@viatropos yes, the installer worked under root permissions to access global folders to place aliasses and so on. i always sudo -g installs, i did it with the 0.4.2-pre also.

well, i never needed homebrew before :)

**Comment by ghost** [comment]
uh, and i wonder about centos installation. @SwarmShepherd  is it fixed?

**Comment by lancejpollard** [comment]
That's why, have you been running all these commands with `sudo` (in the previous comments)?

**Comment by ghost** [comment]
yes, always

**Comment by lancejpollard** [comment]
That's useful info!

Although tower should work with or without sudo, I definitely recommend homebrew, or manually setting up the global node/npm folders so they don't require sudo.

**Comment by ghost** [comment]
well if that so, than the macos installer should take care of it also, should'nt it? :)

**Comment by lancejpollard** [comment]
[http://mxcl.github.com/homebrew](http://mxcl.github.com/homebrew/#selectable) (paste into terminal), then:

```
brew install node
```

You'll never look back.

Installers all have their own conventions of where to install certain files and what permissions they have, and it's up to the individual/team to manage one specific executable (like `node`). If you don't already, you'll start installing mongodb, redis, postgresql, mysql, cassandra, imagemagick, tesseract, git, and more from installers that were each built by different people. What ends up happening is the permissions are all different and unpredictable and you run into issues like this one which take a while to resolve.

The solution is to have 1 interface to installing these command-line tools, and that's what HomeBrew did. It's a huge and dedicated team that's created a library of forumla, which you just run through the command line instead of an installer (https://github.com/mxcl/homebrew/tree/master/Library/Formula). This makes installing any library very predictable.

HomeBrew is one of the most valuable tools I use. I haven't had any problems with permissions/installations since I started using it some 2-3 years ago.

**Comment by SwarmShepherd** [comment]
UPDATING NODEJS (via nvm -  builds from source) to -v 0.8.9  +  updating npm made a big difference.  Install is actually successful and starting the server is successful (now serving on port 3000 mssg) but then chokes and dies on a DB issue yet to be resolved.

I had the (wrong?) 1st impression that HomeBrew is for OSX (only)- but will definitely grab for it next time I have issues like this.  Thanks for hints! 

As a Ruby programmer I have been "spoiled" by a system of tools that have been changing much less rapidly in the last years.  Almost forgot what it was like in the earlier days.  

It will be a day to remember when Node hits 1.0.0  !

Thanks for all the thoughtful and useful comments...
