### ISSUE TITLE
Wiered routing issues with Tower and Ember

### ISSUE THREAD

**Issue by j-mcnally** [tower-archive/tower#273]
if my router says

`@resources "homes"`
and i navigate to `/homes`

everything loads

but if i have

`@match '/', to: 'homes#index'`
and navigate to `/`

nothing happens. I just get my template.

**Comment by maedi** [comment]
Yes I think I'm experiencing this issue as well

**Comment by lancejpollard** [comment]
This is because the client routes are only wired together for `@resources` and `@resource`, we need to make it more robust / add it to the `@match` method. Would you mind taking a look at that? It should be fairly straightforward to implement, see this:
- [packages/tower-net/shared/route/dsl.coffee#L113](https://github.com/viatropos/tower/blob/43f69b9d472fcee852bea5cecbf82e412a7fa56f/packages/tower-net/shared/route/dsl.coffee#L113)

The `state` key that is passed into the `@match` options hash is then handled by the client router:
- [packages/tower-net/client/states.coffee#L90](https://github.com/viatropos/tower/blob/43f69b9d472fcee852bea5cecbf82e412a7fa56f/packages/tower-net/client/states.coffee#L90)

That `insertRoute` method is called for each route defined in the `Tower.Route.draw` DSL, and is passed a `Tower.Route` instance.

Send a PR if you'd like, otherwise I'll be getting back to the routes in a few weeks (though I'll try and get to this one sooner).

**Comment by j-mcnally** [comment]
I'm in I'd love to work on stuff I tried to fix it myself but haven't had a
chance to dig through how everything is currently laid out

**Comment by lancejpollard** [comment]
For sure, let me know where you're at and I'll help where I can.

**Comment by lancejpollard** [comment]
Feel free to send me a PM on Twitter if you're ever digging into code, my phone goes off so I can respond faster :)

**Comment by j-mcnally** [comment]
Thanks so much lance I'm a huge fan of rails but if tower gets better I'd
much rather use it. The ember integration rocks and I'd love to be a
contributor of this awesome platform.

**Comment by j-mcnally** [comment]
this can be fixed in documentation:

adding `action: "index", state: "home.index", name: 'home', method: ['GET']` to the route line

fixes the issues

**Comment by j-mcnally** [comment]
Outstanding is that the `/` route is pushed to `/root` which is a bug that I am looking at now.

**Comment by edubkendo** [comment]
@j-mcnally new guides/documentation on ember's router is really good. May be helpful for understanding how to get them to play well with tower: https://github.com/sgharms/website/blob/160477fd0ab1789915ff46bdceb04a6faa74ef18/source/guides/router_primer.md

**Comment by kennu** [comment]
Does this issue mean that a Tower app cannot have a home page (at /)? I just tried to create a new app, and it doesn't show anything in the home page, except for the surrounding layouts. I.e. whatever I put in app/templates/shared/welcome.coffee is not shown.
