### ISSUE TITLE
Sockets?

### ISSUE THREAD

**Issue by thehydroimpulse** [tower-archive/tower#279]
Just trying to get a simple example for sockets up and running and gotten into a few issues.

Client Post Controller:

``` coffee
class App.PostsController extends Tower.Controller
  @scope 'all'

  @on "getMessage", "getMessage", type: 'socket'

  # @todo refactor
  destroy: ->
    @get('resource').destroy()


  getMessage: (@sockets) ->
    console.log "I am sending a message.", @sockets
```

Server Post Controller:

``` coffee
class App.PostsController extends App.ApplicationController
  @param 'content'

  @scope 'all'

  @on "addMessage", "addMessage", type: 'socket'

  addMessage: (event)->
      console.log event

```

When I run the server I get this console error in the browser:

```
Uncaught TypeError: Cannot call method 'connect' of undefined 
```

Which points to line 13223 in Tower.js:

``` javascript
this.io || (this.io = Tower.Application.instance().io.connect('/' + this.socketNamespace()));
```

There doesn't seem to be a very good explanation on sockets in tower.js.

**Comment by lancejpollard** [comment]
Sorry about that, the socket api has changed a lot since the documentation was made, definitely need to update the docs.

Currently, that method of manually sending data through sockets has been temporarily disabled so we could focus on automatically syncing Model data, which does work and is using sockets.

There's a lot to document so I'll point you to the relevant places in the code. First, the data-syncing is managed via `Tower.NetConnection` instances, which are stored in a `Tower.connections` hash by `socket.id`. On the client there is only 1 id, but the server has many. If you have called `App.listen()` on the client, this should connect the sockets and store the id in `Tower.connections`.

Once that's setup, the `Tower.NetConnection` instance has handlers for when both the client and server create/update/destroy records:
- https://github.com/viatropos/tower/blob/master/packages/tower-net/client/connection.coffee
- https://github.com/viatropos/tower/blob/master/packages/tower-net/server/connection.coffee
- https://github.com/viatropos/tower/blob/master/packages/tower-net/shared/connection.coffee

On the client, if you call `someRecord.save()` on a new record, it will `POST` it to the server. Then on the server, it will call `someRecord.save()`, which will save it to MongoDB. After save on the server the record gets passed through every connection and is sent to the clients that can (or are authorized to) accept it. That occurs here on `Tower.NetConnection#notify`:
- https://github.com/viatropos/tower/blob/master/packages/tower-support/shared/shared.coffee#L41

The other connected clients will then receive the message that a record was created:
- https://github.com/viatropos/tower/blob/master/packages/tower-net/client/connection.coffee#L67

That just loads the JSON for that record into the client-side memory store. This triggers any _registered_ `Tower.ModelCursor`s (Ember.ArrayProxy subclass) to add the record to its collection, which triggers templates to auto-update (such as a list of records, etc.).

The only thing you need to make this auto-updating work is define cursors with `@scope` on the client and server controllers, such as:

``` coffeescript
# server
class App.PostsController extends App.ApplicationController
  @scope 'all'

# client
class App.PostsController extends Tower.Controller
  @scope App.Post.where(createdAt: '>=': _(2).days().ago())
```

The controller scopes/cursors are very primitive at this point but this is the general approach to syncing data via web sockets.

The ability to add `@on 'someMessage'` like you're asking was temporarily disabled so we could flesh out this data-syncing thing. We need to go back and fix that but it may be a few weeks until I can get to that. If you'd like to help get it working I can point you further in that direction, it should be straight forward.

Hope that helps.

**Comment by thehydroimpulse** [comment]
No worries. That sounds great! Thanks for taking the time to explain it. Yeah I'd love to help and give a hand. I'll take a closer look at studying the code once again to understand what's going on. Oh and a quick question for modifying the tower code locally: Do I have to compile all the javascript back into coffeescript? Or download straight from github?

**Comment by lancejpollard** [comment]
Awesome! To modify the tower code, clone the repo, and compile the coffee-script. You can then link it globally and then locally into an app (that's what the contributors are mainly doing):

```
git clone https://github.com/viatropos/tower
cd tower
npm install
# in another terminal window
make watch # compiles everything
# back in the first window
make test # runs all tests, can just do `make test-memory` to only run tests against one store to speed it up.
```

With the watcher running you can change the coffee-script files (everything in `packages`) and it will recompile.

If you want to link it to an app, then:

```
# in the tower repo directory
npm link # links to global npm registry on your computer
# in your app
npm link tower
```

Then whenever you change the tower source, it will be reflected in your app as well (since it's just a symlink).

There are a bunch of tests in `./test/cases`, feel free to modify and send pull requests.

**Comment by thehydroimpulse** [comment]
Ok Awesome! Thanks for the pointers :)
