### ISSUE TITLE
Socket Constraint

### ISSUE THREAD

**Issue by thehydroimpulse** [tower-archive/tower#280]
I started reimplementing / fixing the manual socket manipulation. I'm wondering about adding constraint a on sockets. This would allow you to customize who gets the socket message. Obviously you could parse this on the receiver but it would kinda be a waste of resources if every client gets every notification let's say and then they'd have to see if the message is for them or not.

So what I'm suggesting is a sender constraint that would match to a specific user , role, permission, etc... 

There could be a second hash of connections linking the client ids and session or user ids for example. This would only work if adding constraints is customizable and easy to implement.

``` coffee
@publish type: "/notifications", name: "message", data: @data, constraint: new Tower.Socket.Constraint.Authentication(user_you_want_to_send_to_id)
```

``` coffee
class App.EventController extends App.ApplicationController
 @subscribe type: "/notification", name: "message", method: "getNotification"

 getNotification: (@socket) ->
```

This is an example of the current implementation so far, but the publish and subscribe keywords are just templates for now.

For now I based the constraints on having sub or child classes to where it can customize the constraint. 

``` coffee
class Tower.Socket.Constraint.Authentication

   constructor: (@user_id) ->
       # Hash class will create a new alias connection hash based on it's parameters.
       # Tower.Authentication.match would return a new hash containing the client_id and user_id / session_id. The client id
       # is the same as the id in the original connection hash, the one generated by socket.io 
       # e.g {client_id: "123456789", user_id: "655434544"} ... In this case the user_id is a mongodb document id.
       @hash = Tower.Socket.Constraint.Hash(Tower.Authentication.match(user_id)) 
   get: ->
     @hash
```

In this particular example there would be a mongodb document containing the logged in users or currently active sessions. It would have it's session_id, user_id and socket.io client id. This would be automatically updated by the auth library when a user logins. So the match would go and fetch the user_id thats in the document and return the socket.io client id and it's associative information in a hash. You could easily have this inline within this constraint class but would allow a more modular and separated approach. The only thing to consider is how users could go about create a new set of constraint classes. This could be inside the lib or app folder.

Just an idea.

**Comment by lancejpollard** [comment]
Good stuff! I like where you're headed with it. Some thoughts that come to mind.

First, about applying "constraints" on who can receive what message. @kristianmandrup implemented something very similar to [cancan](https://github.com/ryanb/cancan) in Tower, for authorization, https://github.com/kristianmandrup/beer_can, and I merged some of that stuff in as well. Tower has an alpha-level `Tower.Ability` class that wraps `currentUser` and can be used to test if the user can create/read/update/delete certain data:
- https://github.com/viatropos/tower/blob/master/packages/tower-model/shared/ability.coffee

``` coffeescript
class App.Ability extends Tower.Ability
  assign: ->
    user = @get('user')

    @can 'read', App.Post
    @can 'update', user.get('groups').all()
    @can 'manage', user.get('memberships')
    @can 'read', 'create', App.Membership
    @
```

Technically it works (using it now), but it's not documented. Along the same lines as what you're suggesting, the ideal situation would be something like the following for managing data pub/sub...

There is a global server-side map of socket ids to a `Tower.NetConnection` object. That `connection` object then has a reference to the `user` and `ability`, which in the controller were `currentUser` and `currentAbility`. Then every request - no matter if it's through AJAX,  plain HTTP, Web Sockets, etc. - somehow has an `id` that we can use on the server to find the socket/connection. This would mean we can store all the connected users in memory on the server, which is nice as it would prevent those database calls on every request (which you could cache, but still).

Then, when any data is modified on the server, no matter if it's sent through web sockets or HTTP (or even if it's created through the `tower console`), it iterates through the `Tower.connections` hash, and for each `connection` it tests if the data can be sent to the client - using the `Tower.Ability` exactly like how you're describing the _constraints_.

So the main thing that's still missing is how you define the plain socket handlers (i.e. your `@publish` line). I was just thinking of having an `@on` handler on both the client and server, and on the server you just have a `beforeAction` filter that tests it against the `currentAbility`, and if it's unauthorized then return some error response. Not sure though, since you're digging into this you probably have a better idea, what do you think?

**Comment by thehydroimpulse** [comment]
lol I was on my phone while typing this up and so it switch to contrains instead of contraints.

Anyways, that sounds awesome with the ability class. I just took a look at it a little while ago and that would simplify things. Not sure if you want to have to option to use a different authentication solution or the built-in Tower one? 

Yeah the currentUser and currentAbility objects would simplify the load a little bit. 

I was thinking on the same lines as you according to the @on methods. Right now I'm just using a boilerplate @publish / @subscribe to differentiate the result at first, then once it works i'll merge the syntax into @on since i'll have to make some checks (on the client) whether it's a socket event or not.  

I was thinking of placing the socket accessibility code in the default `Tower.Controller` class, that way you can use @pub / @sub / @on whenever you want. Though an alias to a `Tower.Socket` could make it more modular and separated. 

Actually, I was just browsing inside the tower-controller and the ControllerSockets class has I'm guessing the old code for push notifications? That may be the perfect place to add the pub, sub, on methods:

``` coffee
# @module
Tower.ControllerSockets =
  # @emit 
  publish: (type, name, data, constraint) ->
      Tower.NetConnection.Socket.publish(type,name,data,constraint)

  # @on
  subscribe: ->
      Tower.NetConnection.Socket.subscribe(type, name, method) 
      # You'd have to get the actual method, as it would just be simple text.

module.exports = Tower.ControllerSockets
```

An example of a possible lambda function with sockets: 

``` coffee
class App.AdminController extends App.ApplicationController

  @subscribe type: "/notification", name: "message", method: -> (socket)
      # Do something in here. This could possibly cut down on boilerplate code.

```

So i'll check up on the Ability class and the Authentication so far, though I might add some stuff to make it more of an Authentication Library backed by passport, instead of just being powered by passport. But I'll try to make it modular so that someone can use their own implementation of an authentication or should it be bolted in?

**Comment by lancejpollard** [comment]
Ha, that's way too much to type on a phone :)

Yeah man this looks great, I'm on board with the stuff you're describing.

The only thing that's unclear to me in looking at it is the `type: "/notification"`. [Remembering now] In the initial implementation, what you're calling `type` we just had be the controller name pluralized, and then your `name: 
"message"` was just the method called on the controller. So this:

``` coffeescript
@subscribe type: "/notification", name: "message"
```

was this:

``` coffeescript
@subscribe 'message'
```

where the `type` would be `/posts` for example, if it was in the `App.PostsController`.

Let's aim to use the controller/routing conventions for the sockets unless there are common cases where you'd need more robust functionality.

Feel free to send a PR once you get something started, I'd love to take a look.

**Comment by thehydroimpulse** [comment]
haha ok sounds good! Yeah thats a much cleaner syntax! 

I'll go continue implementing all this stuff and i'll get back to you when I got something working!

**Comment by lancejpollard** [comment]
Sweet

**Comment by kristianmandrup** [comment]
"Authentication so far, though I might add some stuff to make it more of an Authentication Library backed by passport, instead of just being powered by passport. But I'll try to make it modular so that someone can use their own implementation of an authentication or should it be bolted in?" 

Hmm, we had some discussion about Auth libraries previously in a different issue thread I think. Maybe you can get some input from there and pseudo-code etc. as well for inspiration. I think it would be nice if Tower came with a simple Auth lib "built-in" while still making it easy to extend this or add a custom one. This is such core functionality for almost any web app. I also see a strong move to using Auth provider solutions over having a complete "auth solution" in every app... Nice to her that my BeerCan project was useful. I never got around to finish it off.. Cheers!

**Comment by thehydroimpulse** [comment]
Yeah i'll take a look at the previous issues. Yeah a nice authentication solution that has much of the boilerplate code would be best. Then if other users want all the extra bells and whistles they could implement a driver or something. 

Though to make the constraints and the sockets work a little better, there's gonna need an auth solution to combine everything or centralize it.

Just some thought,
Cheers!

**Comment by kristianmandrup** [comment]
So did this get completely resolved now? Do we have a socket solution with security i.e. authentication/authorization that can be configured on top or what? I'm just starting to get back on board with Tower again... Now with some basic knowledge of Node, Express etc. I'm ready to dig in this time!

**Comment by thehydroimpulse** [comment]
@kristianmandrup So Lance mentioned on the other issue that we:
- Moved to pure JavaScript. Coffeescript became a huge burden (probably because of how it was being built). Now it's much simpler for people to jump right in.
- Everything is separated into individual modules (https://github.com/tower). This creates a slight burden on getting the development environment up and running as you need to clone many of the repos (and there's a lot of them). I'll probably work on this within the next 3 weeks and get it working extremely well to where you can just clone the main Tower repo and they'll be a executable you can run that'll clone everything for you.

Other Stuff:
- We dropped Ember.js on the front-end. Ember is the bigger client-side framework today (that's popular). It was also extremely hard to always wrap around Ember and work with it. We decided to drop it in favour of starting from scratch on the client-side with components. This allows to have a fully modularized client-side environment. We already have a lot of progress on the client-side.
- A DOM-based templating engine. Similar to Batman and Angular, where we use DOM attributes to embed data bindings and logic with some use (very little) of a mustache-like syntax `{{var}}`. That's just used for tiny inline interpolation.
- Currently, we're transitioning to a Koa backed server system, instead of express. Koa is authored by the same guy (TJ) as the one who created Express and Connect. It's basically like a new connect that's much more slimmed down and uses Co to use harmony generators. This allows you to build everything in a synchronous style, avoiding the callback hell.

``` js
var route = require('tower-route');

route.get('index', '/')
 .action(function*() { // Note the `*` symbol to denote the generator.
   this.scope.users = yield model('users').all(); // Yielding will "pause" the function as we perform the operation.
   this.render('index');
 });
```
- We're developing a lot of the environment so you can quickly get to building the actual web app. This includes having a Meteor-like development style, but better. Everything will be modular, we'll be using NPM and Components for client and server modules respectively (and a higher-level package system that combines the two...). I'm currently building the asset builder/pipeline that'll automatically reload the server process (thanks to tower-proxy) and will save the current state in the browser, reload the page, then restore the state (much like Meteor).
- A consistent API for almost everything on the client and server-side. The context might just vary.

``` js
model('users').find(1);
route('index').action();
resource('user');
...
```

So all in all, we have a much clearer vision with an EXTREMELY modular backbone (especially with the recently added Tower modules - Not implemented yet thought). This definitely speeds up development and helps concentrating on specific pieces. It's also all about separation of concerns. Modules do ONE thing and does that thing very well. The templating system (server-side) is backed by at least 6-7 modules. I might also separate it even more.

Just an fyi, the templating system:

``` html
<!-- Main Template -->
<!DOCTYPE html>
<html>
  <head>
    <title data-text="title"></title>
    <div data-import data-load="app" data-type="css"></div> <!-- Will be converted appropriately -->
  </head>
  <body>
    <div data-child></div> <!-- Similar to Ember's {{outlet}} -->
    <div data-import data-load="app" data-type="js"></div>
  </body>
</html>
```

Template

``` html
<h1>Hello World</h1>
```

is powered by the [tower-server-dom](https://github.com/tower/tower-server-dom) which is a new HTML5 DOM implementation in Node that's super lean and clean that uses Gumbo (Open sourced by Google).

Anyways, that's just an overview of what's going on.

**Comment by kristianmandrup** [comment]
Wow! Thanks a lot for the update @TheHydroImpulse :)
It looks like you are definitely on the right track with many of these development!! I embrace the fact that you dropped Ember.js. I spent a month trying to get my grips on it and then pulled away and never looked back. I also felt it was way to inflexible for customization etc.

Excited about Koa and Co. You might consider Bacon.js as weel to simplify working with event steams.

I'll defintiely look more into Tower and see if I can contribute! Great work guys :)

**Comment by kristianmandrup** [comment]
I am curious to know why you decided to implement your own directives implementation similar to fx Angular and Derby and not just let the user leverage Angular directives (via Angular) if he so chooses?

**Comment by thehydroimpulse** [comment]
@kristianmandrup Angular's codebase is so monolithic and mixed together with everything else, it's impossible to reuse anything. We also make heavy use of components and creating super small, compose-able modules that people can use with Tower, or without. It's not tied to Tower directly, it may just depend on a few more Tower modules that are again, super small and simple.

We also simplified the system greatly. Our goal for the templating system is to merge some of Ember's performance like their runloop which I reimplemented in a modular, super small component. 

We also didn't really want to depend on another framework. Angular is fairly opinionated and it probably wouldn't work to wrap it as we did with Ember.

**Comment by kristianmandrup** [comment]
Awesome! I think it's the right way to proceed and move forward. We keep learning from past mistakes and other frameworks that get bogged down by complexity and become too monolithic... I'm just learning the power of TRUE functional programming done right, like Bacon.js and others, fx using currying to tidy up and making the code super pretty and DRY.

http://hughfdjackson.com/javascript/2013/07/06/why-curry-helps/

https://github.com/CrossEye/ramda

http://allong.es/

https://github.com/baconjs/bacon.js

I think using this style of coding is the future for sure and would be a great addition to your framework. Is the style that all frameworks need now in order to move forward I think. OK, sorry, I know this is not the forum for this kind of discussion - but just very excited to have my eyes opened to a radically different but beautiful new style of coding that is so sweet :)

When I'm up to speed with this new style I will gladly help out and use your framework and start improving documentation and main screencasts. Haven't been so excited since I switched from Java to Ruby and then Rails... and lately to Node.js. Cheers!

``` javascript
return mapWith(maybe(getWith('name')))(customerList);
```

Instead of:

``` javascript
return customerList.map(function (customer) { if (customer) {
return customer.name }
});
```

**Comment by thehydroimpulse** [comment]
Awesome, and no worries. 

I'm a huge proponent of functional programming. I've mainly done work in Lisp and Lisp dialects such as Clojure, Scheme, etc... Clojure is an amazing platform and it gets you thinking beyond traditional imperative programming.

That's why our API is mostly composed of flat functions. Now, it's hard to be truly functional in JavaScript with immutable data and such, but the API is primarily just made up of functions that have some chain-ability. 

I haven't spent too much time with Bacon.js, but it looks really interesting. I spent some time reading about functional reactive programming.
