### ISSUE TITLE
Config.server.assets

### ISSUE THREAD

**Issue by ivoreis** [tower-archive/tower#282]
Hi there!

I was checking out how this framework work and i'm getting a hard time figuring all up. I know that this awesome framework is under heavy development and in a very early stage and a lot is being done, but the documentation is not helping the new guys that arrive to this project. I'm just saying this because some information that can be found on the website is not fresh and updated and can give a lot of people some nasty headaches :) 

So back to the question,  when we create a new model / controller or folder with Mailers, inside the app folder, do we need to add them to the config.server.assets or its all wired up like rails and are in auto-load path? 

I'm just figuring this all up but if i can support in anything i'll be glad to help.

Nice job with this project Lance!

Cheers!

**Comment by lancejpollard** [comment]
Hey!

Thanks for posting. You're totally right with the docs, they are way out of date. Knowing that it's a big barrier to new guys coming to the project is very useful info, I'll make it a higher priority to update them soon. For now though the best documentation is just in reading the code since things are changing so fast, but we will have docs at some point (which the website will reflect).

The official "docs" are stored here: https://github.com/viatropos/tower-docs. They also haven't been updated in a while but they are more up-to-date than the website. Feel free to send pull requests to the tower-docs repo as you learn things, that would really help for the newcomers.

Right now assets are auto-loaded on the server, but require manually specifying them for the client. Here are the folders currently auto-loaded on the server:
- [packages/tower-application/server/application.coffee#L12](https://github.com/viatropos/tower/blob/73287445988bafb0590f0e2388f1f0b3069368d5/packages/tower-application/server/application.coffee#L12)

For the client though, you have to add them to `app/config/server/assets.coffee`:
- [packages/tower-generator/server/generators/tower/app/templates/app/config/server/assets.coffee](https://github.com/viatropos/tower/blob/73287445988bafb0590f0e2388f1f0b3069368d5/packages/tower-generator/server/generators/tower/app/templates/app/config/server/assets.coffee)

When you generate a model for example, such as `tower generate scaffold post`, it will inject `/app/models/shared/post.coffee` (and others) into `app/config/server/assets.coffee` automatically. I may add to the grunt/watch task a feature where when you create a file in `app/models`, for example, it will inject it into the assets.coffee file, but this may be more complicated than it's worth.

The reason for having to manually specify the client assets is that Tower currently doesn't have any sort of browser package manager integrated (such as bower or require.js). Eventually we should do this but when I have tried in the past it ended up being too complicated and time consuming; things have changed since then though so it may be good to take another look at it.

Finally, the contents of `app/config/server/assets.coffee` is stored in `Tower.config.assets`:
- [packages/tower-application/server/application.coffee#L238](https://github.com/viatropos/tower/blob/73287445988bafb0590f0e2388f1f0b3069368d5/packages/tower-application/server/application.coffee#L238)

Cheers!
