### ISSUE TITLE
Human Readable Database Results

### ISSUE THREAD

**Issue by maedi** [tower-archive/tower#300]
When querying Mongo from the Controller we get back quite a big soup of variables, which e_dub mentioned in IRC are for Ember integration.

```
posts = App.Post.all()
```

As a new user I found this confusing, expecting to get the results themselves. I'm sure they're in there but I can't see them in the console as there are too many lines for the terminal window to keep track of.

e_dub suggested using this to get the first object:

```
posts.objectAt(0)
```

But for example, how would I loop through each result? Seeing a simple array of results would allow users to visualize the data set much easier. Do we need a "dataFilter()" function?

**Comment by lancejpollard** [comment]
Not quite sure what you're asking, are you wondering about the terminal and how to see/inspect data there?

To do that there is a helper function `_.stringify(App.Post.all()`, which just calls `JSON.stringify(records, null, 2)`, but that can be overwhelming.

What do you suggest? Should there be a more robust database-like (mysql-like perhaps) set of helpers for visualizing the data something like this:

[![MySQL Data](http://i.imgur.com/Kyhi3.png)](http://dev.mysql.com/doc/refman/5.1/en/explain-extended.html)
![MySQL Record Data](http://i.imgur.com/XGag4.png)

Two things actually. First, there should probably be a `tower database --mongodb` or `tower <database>` command to directly startup the database. Some people seem to use this (though I never have). Second, we should provide a standard set of "data formatting" helpers in the console (and browser) for visualizing the data:
- in table format (first image above)
- show individual record (second image above)
- in json
- etc.

[![Twitter Command Line](https://raw.github.com/sferik/t/master/screenshots/list.png)](https://github.com/sferik/t)

**Comment by maedi** [comment]
`_.stringify` is the sort of thing I'm after, thanks. In a perfect world `App.Post.all()` would return this too. Even though it's overbearing, it's actually doing what the `.all()` implies, rather than an Ember object.

Regarding MySQL, I've found MongoHub (Mac) can help to visualize the data if you click the 'Query' icon.

With the database console idea, this sounds really useful. I'm currently using something like this to reset my DB, but not to inspect:

```
mongo
show dbs
use [databasename]
db.dropDatabase();
```

**Comment by edubkendo** [comment]
To loop through the results what I usually do is something like:

``` coffeescript
App.User.all (err, users) =>

  App.User.count (err, count) =>

    for num in [0...count]
      user = users.objectAt(num)
      console.log user.toJSON()  #this will show you just the user object and it's properties.
      # do something to user
```

It's slightly awkward, but a small price to pay for the conveniences Ember brings.

**Comment by lancejpollard** [comment]
Started messing around with a cli to the database:
- https://github.com/viatropos/tower/commit/dd17e4dbd7732c560517933536cc17638ca16de5

For now you can just quickly query data:

```
tower select posts --select id,createdAt --where 'createdAt: $gte: _(1).days().ago()' --order createdAt- --limit 10 --page 2
```

![Tower `select` command](http://i.imgur.com/gPPng.png)

Eventually it could even be such that:
- the printed table is an editable spreadsheet in the terminal, so you can actually modify the raw data directly. The hardest thing was figuring out how to get the position of the terminal's cursor and map it a line of text - then to a model. But [ansi.js figured it out](https://github.com/TooTallNate/ansi.js/blob/master/examples/cursorPosition.js)! Here is another hack I tried that works, but ansi.js is way better :) https://gist.github.com/3765464
- you can quickly paginate the database (and queries) using keyboard shortcuts in the terminal.
- when you edit data in there, it could autocomplete from the rest of the db data.
- similar visualizations/functionality should be possible from within the `tower console` js/coffee environment somehow.

It's not that bad once it gets figured out how to scroll the terminal cursor up and down and map that to data. Theoretically you can even build a DOM in the terminal using [cheerio](https://github.com/MatthewMueller/cheerio). It looks like that's what he started here!
- https://github.com/Marak/ANSIdom

All we'd have to do is customize the `cheerio.render` method to generate ASCII / ANSI strings instead of HTML... Could easily be done in a day!
- https://github.com/MatthewMueller/cheerio/blob/master/lib/api/render.js

Here are some other links for learning about ANSI escape sequences (which give you crazy terminal powers):
- https://github.com/crcn/celeri
- http://blog.nodejitsu.com/six-nodejs-cli-apps
- http://stackoverflow.com/questions/10585683/how-do-you-edit-existing-text-and-move-the-cursor-around-in-the-terminal/10830168#10830168
- https://github.com/hij1nx/cdir/blob/master/cdir.js#L26
- https://developer.apple.com/library/mac/#documentation/opensource/Conceptual/ShellScripting/AdvancedTechniques/AdvancedTechniques.html
- http://tldp.org/HOWTO/Bash-Prompt-HOWTO/x361.html
- http://nodejs.org/api/tty.html
- https://github.com/TooTallNate/ansi.js
- http://en.wikipedia.org/wiki/ANSI_escape_code
- https://github.com/mscdex/node-ncurses
- https://github.com/jocafa/node-term-ui
- https://github.com/chjj/pty.js/
- https://github.com/SchizoDuckie/Node-CLI
- https://github.com/substack/node-cursory
- testing clis: https://github.com/LearnBoost/cli-table/blob/master/test/index.test.js
- https://github.com/visionmedia/node-term-css
- http://creativejs.com/2012/02/ansi-escapes-js/
- http://stackoverflow.com/questions/2575037/how-to-get-the-cursor-position-in-bash
- http://stackoverflow.com/questions/8343250/how-can-i-get-position-of-cursor-in-terminal
- http://www.markcrocker.com/rexxtipsntricks/rxtt28.2.0773.html
- https://github.com/unconed/TermKit
- http://scie.nti.st/2006/12/19/vi-key-bindings-in-rails-console
- http://stackoverflow.com/questions/9122282/how-do-i-open-a-terminal-application-from-node-js
- http://www.brankovukelic.com/post/2091037293/turn-vim-into-powerful-javascript-editor
- http://railscasts.com/episodes/48-console-tricks-revised?view=comments

Cheers.

**Comment by maedi** [comment]
Cool! This could be quite powerful...
