### ISSUE TITLE
Nested resource 'new' action incorrect 'Submit' link

### ISSUE THREAD

**Issue by maedi** [tower-archive/tower#304]
I have 2 resources, a Shop and a Product:

``` coffeescript
class App.Shop extends Tower.Model
  @field 'name', type: 'String'
  @hasMany 'products'
  @timestamps()
```

``` coffeescript
class App.Product extends Tower.Model
  @belongsTo 'shop'
  @field 'name', type: 'String'
  @field 'price', type: 'Float'
  @field 'shopID', type: 'String'
  @timestamps()
```

With a nested route:

``` coffeescript
Tower.Route.draw ->
  @resources 'shops', ->
    @resources 'products'
```

But when I create a new shop product at "shopProducts/new", manually pasting in the ShopID and clicking 'Submit', the Firebug Console says:

> POST http://0.0.0.0:3000/products 404 Not Found

Shouldn't it be POSTing to shopProducts?

**Comment by thehydroimpulse** [comment]
Could you post your views? Specifically where the new link is?

**Comment by maedi** [comment]
The _form.coffee template in "templates/shared/products":

``` coffeescript
text '{{#with resource}}'
form ->
  fieldset ->
    ul class: 'fields', ->
      li class: 'control-group', ->
        div class: 'controls', ->
          label 'Name:'
          text '{{view Ember.TextField valueBinding="name"}}'
          text '{{#with errors}}'
          span class: 'help-inline error', '{{name}}'
          text '{{/with}}'
      li class: 'control-group', ->
        div class: 'controls', ->
          label 'Price:'
          text '{{view Ember.TextField valueBinding="price"}}'
          text '{{#with errors}}'
          span class: 'help-inline error', '{{price}}'
          text '{{/with}}'
      li ->
        a '{{action submit target="resource"}}', 'Submit'
text '{{/with}}'
```

In the Views directory there are product views for edit, index and show, but no 'new'. Could this be it?

**Comment by thehydroimpulse** [comment]
Did you generate through scaffolding?

**Comment by maedi** [comment]
Yes

**Comment by thehydroimpulse** [comment]
mmm. I'm assuming you are using views within the templates directory? When I used the scaffold it generated all of the required files including *_new.coffee_. When I rename the new.coffee file the app doesn't break....... I'm probably too tired and doing something wrong. If no one gets to this by the morning i'll take a shot.

**Comment by maedi** [comment]
Here's what I see:

![Tower Files](http://i.imgur.com/zwJqz.png)

**app/templates/shared/products/new.coffee**

``` coffeescript
@title = "New Product"
partial "flash"
partial "form"
```

And the form partial that this references is above.

**app/views/client/products/form.coffee**

``` coffeescript
App.ProductsEditView = Ember.View.extend
  templateName: 'products/edit'
  resourceBinding: 'controller.resource'
  # You can also use an object controller (Ember.ObjectProxy) 
  # as a layer between the view and the model if you'd like more control.
  # resourceControllerBinding: 'controller.resourceController'

  submit: (event) ->
    # @todo
    # if @get('resource.isNew')
    #   @get('controller.target').send('createProduct')
    # else
    #   @get('controller.target').send('updateProduct', @get('resource'))
    @get('resource').save()
    Tower.router.transitionTo('products.index')
    return false

```

**Comment by lancejpollard** [comment]
I think this is because "nested resources" aren't yet setup on the ember side.

Do you only have a server-side nested route for `@resource 'shop', -> @resources 'products'`? (I'm guessing that's why the 404 on `/products`).

The `@get('resource').save()` is always going to save using the top-level route [currently]. We need to flesh this out more, specifically:

What should the API be when you have **multiple routes for a single "record"**? So top-level `/products` and nested `/shop/products` or whatever.

_Sidenote: I understand that in the ideal REST case, there is only 1 URL for a resource, but practically it's common and useful to have multiple - particularly for scoping resources to some parent model._

Currently you can generate the two different urls like this:

``` coffeescript
shop = App.Shop.first() # id: 10
product = App.Product.first() # id: 20

Tower.urlFor(product) #=> '/products/20'
Tower.urlFor(shop, product) #=> '/shops/10/products/20'
# I don't think we've handled singular routes yet, so this isn't possible:
# Tower.urlFor(shop, product) #=> '/shop/products/20'
# You'd have to do this:
# Tower.urlFor('shop', product) # a namespace
```

See the `urlFor` tests for more examples (they need to be reorganized):
- https://github.com/viatropos/tower/blob/master/test/cases/support/shared/urlTest.coffee
- https://github.com/viatropos/tower/blob/master/test/cases/net/shared/urlForTest.coffee

When you call `resource.save()`, that goes eventually to `Tower.StoreTransportAjax#create`:
- [https://github.com/viatropos/tower/tree/master/packages/tower-store/client/transport/ajax.coffee#L117](https://github.com/viatropos/tower/blob/c17541d8627ecaca7386e40d99c07ecd1977986d/packages/tower-store/client/transport/ajax.coffee#L117)

[Working on the API for that module, it's far from ideal now]

The `create`, `update`, `destroy`, and `find` methods in that Ajax module get the url by calling `urlForCreate(record)`, etc.:
- [https://github.com/viatropos/tower/tree/master/packages/tower-store/client/transport/ajax.coffee#L132](https://github.com/viatropos/tower/blob/c17541d8627ecaca7386e40d99c07ecd1977986d/packages/tower-store/client/transport/ajax.coffee#L132)

They're very primitive, but that's where your issue is probably. Somehow we need to come up with an API to allow nested resource URLs to be generated instead of the `/products`.

Open to suggestions, what are your thoughts?

**Comment by lancejpollard** [comment]
Ember has a method, `urlForEvent`, that I know I was able to use on the controller, which gets passed the "context" from the `{{bindAttr showPost post href=true}}`, you might want to check into that:
- https://github.com/emberjs/ember.js/blob/master/packages/ember-routing/lib/router.js#L515

Potentially it could be added to the generated `Ember.Route` instances in Tower too:
- https://github.com/viatropos/tower/blob/c17541d8627ecaca7386e40d99c07ecd1977986d/packages/tower-net/client/states.coffee#L50

That `urlForEvent` method works along the same lines as `serialize` and `deserialize` there.

**Comment by maedi** [comment]
Yes I only have a nested route in `app/config/shared/routes.coffee`. How do I modify the nesting for the Ember/client side of things? Maybe routes.coffee shouldn't be in the `shared` folder?

**Comment by lancejpollard** [comment]
The main issue is `resource.save()`, which [currently] will always save to the `/<model-name-plural>` path, from here:

[packages/tower-store/client/transport/ajax.coffee#L132](https://github.com/viatropos/tower/blob/c17541d8627ecaca7386e40d99c07ecd1977986d/packages/tower-store/client/transport/ajax.coffee#L132)

So the only way to do this now is to either override that method or to add a top-level route for the server that is `@resources 'products'`. I'm looking into a more robust API for this but that's all you can really do now.
