### ISSUE TITLE
Scope-binding and client-side syncing. 

### ISSUE THREAD

**Issue by edubkendo** [tower-archive/tower#305]
As mentioned in [Issue #302](https://github.com/viatropos/tower/issues/302) , when you create a model instance in one browser, it instantly appears in all others due to the scope-binding magic inherent in tower. Editing and destroying those instances, however, does not have the same effect. In those cases, the changes do not show up until you actually refresh the other browser. Not sure why this is. With delete, I had to call destroy directly from the model which may be preventing it from triggering the scope, but I'm not sure.

**Comment by lancejpollard** [comment]
The `update` and `destroy` methods on a record weren't fully finished so they have been commented out. Getting them going should be straight though. If you're down to check it out the relevant code is here:
- [Tower.ModelCursor#create packages/tower-model/shared/cursor/persistence.coffee#L94](https://github.com/viatropos/tower/blob/c17541d8627ecaca7386e40d99c07ecd1977986d/packages/tower-model/shared/cursor/persistence.coffee#L94)
- [Tower.ModelCursor#update packages/tower-model/shared/cursor/persistence.coffee#L111](https://github.com/viatropos/tower/blob/c17541d8627ecaca7386e40d99c07ecd1977986d/packages/tower-model/shared/cursor/persistence.coffee#L111)
- [Tower.ModelCursor#destroy packages/tower-model/shared/cursor/persistence.coffee#L128](https://github.com/viatropos/tower/blob/c17541d8627ecaca7386e40d99c07ecd1977986d/packages/tower-model/shared/cursor/persistence.coffee#L128)

They were commented out because the way I was originally updating the Ember.View collections (rendering a list of models for example) was slow when it had to recompute the changes, whereas with create it just pushes. On the todo-list, would love your help. Let me know.

**Comment by edubkendo** [comment]
A bit stuck, changed tower-model/shared/cursor/persistence.coffee like this:

``` coffeescript


  _destroy: (callback) ->
    if @instantiate
      iterator = (record, next) ->
        Tower.notifyConnections('destroy', [record])
        record.destroy(next)

      @_each(@, iterator, callback)
    else
      @select('id').find (error, recordsWithOnlyIds) =>
        @store.destroy @, (error, records) =>
          Tower.notifyConnections('destroy', recordsWithOnlyIds) unless error
          callback.call(@, error, records) if callback
        # this should go into some Ember runLoop thing
        # it should also be moved to the store
    @
```

So now the connection fires to the clients like it should, but the record is still not removed in other clients. It looks like in tower-model/shared/persistence.coffee there is an unload function which gets called on the other clients. This is getting called like it should, but then the function it in turn calls never fires for some reason. It's twin "load" function, which gets called on create, etc does just what its supposed to. I can't figure out why the heck the unload never fires. If you put a console.log above the call that goes, but the call itself does not.

**Comment by edubkendo** [comment]
What those load and unload functions are calling are parallel load and unload functions in tower-store/shared/memory/persistence.coffee. At least, that seems to be it.

**Comment by lancejpollard** [comment]
I think the issues is/was that `mergeDeletedRecords` on the controller doesn't do anything yet. That gets called at the end of this chain:
- `Tower.NetConnection#serverDidDestroy`: [packages/tower-net/client/connection.coffee#L73](https://github.com/viatropos/tower/blob/874573fac7d6c369c173b276bf2074655b03961e/packages/tower-net/client/connection.coffee#L73)
- `Tower.StoreMemory#unload`: [packages/tower-store/shared/memory/persistence.coffee#L52](https://github.com/viatropos/tower/blob/874573fac7d6c369c173b276bf2074655b03961e/packages/tower-store/shared/memory/persistence.coffee#L52)
- `Tower.notifyConnections`: [packages/tower-support/shared/shared.coffee#L41](https://github.com/viatropos/tower/blob/13ba434ad7c38e8c933dd32eb06c1c11c09ef30b/packages/tower-support/shared/shared.coffee#L41)
- `Tower.NetConnection#notify`: [packages/tower-net/client/connection.coffee#L38](https://github.com/viatropos/tower/blob/13ba434ad7c38e8c933dd32eb06c1c11c09ef30b/packages/tower-net/client/connection.coffee#L38)
- `Tower.NetConnection#resolve`: [packages/tower-net/client/connection.coffee#L44](https://github.com/viatropos/tower/blob/13ba434ad7c38e8c933dd32eb06c1c11c09ef30b/packages/tower-net/client/connection.coffee#L44)
- `Tower.Controller#resolveAgainstCursors`: [packages/tower-controller/shared/scopes.coffee#L68](https://github.com/viatropos/tower/blob/13ba434ad7c38e8c933dd32eb06c1c11c09ef30b/packages/tower-controller/shared/scopes.coffee#L68)
- `Tower.ModelCursor#mergeDeletedRecords` -> `Tower.ModelCursor#pullMatching`: [packages/tower-model/shared/cursor/finders.coffee#L113](https://github.com/viatropos/tower/blob/13ba434ad7c38e8c933dd32eb06c1c11c09ef30b/packages/tower-model/shared/cursor/finders.coffee#L113)

I never fully tested/got-working that `@removeObjects` in Ember, there were some issues with it a few months ago but a lot has changed since then. Try testing/breakpointing on the client that when deleting a record it gets deleted, the code gets executed all the way to `Tower.ModelCursor#mergeDeletedRecords`.

**Comment by edubkendo** [comment]
Got destroy working yesterday, problem was a mistyped variable name. Update is proving trickier. Problem seems to be that when you call load for update, it swaps out the action so when it goes to resolveAgainstCursors, the wrong action shows up (load instead of update). That was pretty easy to hack around, but if you DO set it up so that the action stays update, it gets caught in a never-ending loop of update notifications and the original client keeps pinging the server with the update over and over. Kind of stuck here now.

**Comment by edubkendo** [comment]
Should add, these are problems beyond the initial fact that the persistence methods for update and delete don't return a record, so those had to be modified to send the right thing instead of sending the result of the action, which was "undefined"
