### ISSUE TITLE
Merge default Templates into Views

### ISSUE THREAD

**Issue by maedi** [tower-archive/tower#307]
Currently it's confusing having `app/templates` in a separate location to `app/views`. I'm assuming `templates` are just 'partials' that are used by Ember views?

From a file structure point of view there's a bit of a disconnect... it feels like MVTC rather than MVC at the moment. Ember allows us to embed templates inline rather than in a separate file.

**Instead of this:**
_app/views/posts/show.coffee_

``` coffeescript
App.PostsShowView = Ember.View.extend
  templateName: 'posts/show'
```

_app/templates/posts/show.coffee_

``` coffeescript
@title = "Post"

partial "flash"

text '{{#with resource}}'
dl class: "content", ->
  dt "Title:"
  dd '{{title}}'
text '{{/with}}'
```

**Can this be the default?**
_app/views/posts/show.coffee_

``` coffeescript
App.PostsShowView = Ember.View.extend
  template: Ember.Handlebars.compile(

    @title = "Post"

    partial "flash"

    text '{{#with resource}}'
    dl class: "content", ->
      dt "Title:"
      dd '{{title}}'
    text '{{/with}}'
  )
```

Though this example after code doesn't work because there's a scoping issue.

Or is some view related code meant to go in the bare view file? Otherwise I think it's simpler to let the developer create a separate template file when required. It would also reduce the confusion arising from duplicate file names.

**Comment by maedi** [comment]
I can see that some views have submit actions and bindings as well, though I don't see a reason why this can't all be included in the one file?

``` coffeescript
App.PostsEditView = Ember.View.extend
  templateName: 'posts/edit'
  resourceBinding: 'controller.resource'
  # You can also use an object controller (Ember.ObjectProxy) 
  # as a layer between the view and the model if you'd like more control.
  # resourceControllerBinding: 'controller.resourceController'

  submit: (event) ->
    # @todo
    # if @get('resource.isNew')
    #   @get('controller.target').send('createPost')
    # else
    #   @get('controller.target').send('updatePost', @get('resource'))
    @get('resource').save()
    Tower.router.transitionTo('posts.index')
    return false
```

**Comment by j-mcnally** [comment]
theres a bit of awkward ness with ember coming into play here i think

grunt actually compiles all your templates into /public/javascripts/templates.js take a look, i havent looked at how to abstract this but i think its the reason this wouldnt work as simple as you think it might.

**Comment by maedi** [comment]
Oh okay, would love to hear viatropos's thoughts on this...

**Comment by lancejpollard** [comment]
The main reason for the separation is that it should be possible to use the "templates" on the server (e.g. server-generated HTML). If you put the templates into the Ember View then you couldn't use them on the server.

Also, this distinction seems to be common in the Ember/JavaScript community in general:
- ember-rails: https://github.com/emberjs/ember-rails/blob/3a9e90239dfd809e3158d0a936872237f50d267c/lib/generators/ember/view_generator.rb#L12
- chaplin (an mvc layer on top of backbone, this is an example app): https://github.com/chaplinjs/facebook-example/tree/master/js

I think the disconnect is in coming from Rails, where what they called "views" we're now calling "templates". I think that is more of a Rails issue than anything (since Rails was purely server, it didn't have to make the "templates" distinction).

However, I don't think adding the "templates" concept turns MVC into MVTC. Conceptually you know the "templates" and "views" are tied together and part of the "view" layer in MVC.

If you went down that road (MVC->MVTC), then "events" and "routes" and all that other stuff would make it MVTERC... You know what I mean. Also, people in the Rails community often add "presenters" to their apps, which makes it more of an MVP, but they also have controllers..

In the end though, everyone agrees _generally_ on what MVC means, even if things are broken down a little further in practice.

I don't think breaking the MVC into more clearly defined sub-components is a bad thing.

Some other benefits of separate "templates" from "views":
- It makes the code DRY (so you can use "templates" on just the server, or in Ember "views" on the client, for example)
- It makes it so you encapsulate your logic a little better (methods/etc. go into `Ember.View` objects rather than the templates, etc.).
- Also, by having the templates separate, we can run precompilers and other optimizations on them separately from the Ember.View (such as precompiling jade templates).

**Comment by edubkendo** [comment]
In working with ember, and building a rails/ember app a while ago, I looked at tons of ember applications and never saw the templates included in the view. They were always either separated out into their own template files, or else included in html and then referenced from the ember.view. Here's one really good example: https://github.com/joliss/better-tweet-feed . Notice how even though she keeps all her views together in this file: https://github.com/joliss/better-tweet-feed/blob/master/app/assets/javascripts/views.js.coffee , the templates have a folder of their own dedicated to them: https://github.com/joliss/better-tweet-feed/tree/master/app/assets/javascripts/templates . To me, this makes a lot of sense, because in the templates you have a description of the pages structure, leaving the views to handle the code that backs that structure up. 

I think what makes this harder than anything is that tower is something brand new. Nobody else has done exactly what tower is attempting to do, so we don't have clear reference points for how to use all these different parts that tower has. As people begin putting together examples and tutorials and guides over the next few months, and tower's documentation improves, it will begin to become more clear how these parts work together and how best to use them to make the apps you want to make. To top things off, Tower changed massively about a month ago, when @viatropos merged in the code from Ember, and so even the few people like myself who have been working with and playing with tower for several months now are learning our way around again.

Ember itself was essentially designed to be used in a particular way (though part of its strength lies in the way it's been built as a system of smaller packages so that any part or part of it can be used seperately), as one component in a system of other components (including Rails, Ember.Data, etc) so even existing ember documentation, guides and tutorials can only help us so much. Many of the idioms and whatnot I learned while working on that rails/ember app are suddenly of no use with Tower, because those other parts are not there, or because Tower brings the two routers together. Now instead of having essentially a "dumb" server side JSON API, with most/all of your logic on the client, you have a much more symbiotic system thats entwined far more closely. It's a complex thing, and it is still under construction.

All this said, I want to encourage you to continue working with tower. I believe strongly this is the way forward, and just because it seems unclear now how best to use it, doesn't make it any less awesome. Once we find our footing with Tower, we'll be masters of something incredibly useful, tremendously powerful, and far more capable of making the kinds of awesome applications we all want to be making. It may seem difficult now, but everything about tower exists to make development easier.

**Comment by maedi** [comment]
I now agree. Would just add that if `templates` are within the `views` paradigm, then maybe their folder structure should be `views/templates`. As a new user this would have made more sense to me. I think the extra click is worth it (or you can get rid of `server` and `shared` inside `templates` since it is the View/Tower that decides between client or server render.

Though this does appear to be a technical limitation. While a purely client-side EmberJS application might make sense with templates, Tower has a different architecture that makes more sense with the view and template merged. Agree that Rails is the way I'm thinking here, but so will a lot of converts.

> I think the disconnect is in coming from Rails, where what they called "views" we're now calling "templates".

What are our views then? Because of EmberJS they look more like controllers. I guess this is another architectural difference between server MVC and client MVC.

**Comment by edubkendo** [comment]
Controller's (I think I understand) handle what happens as you go from state-to-state, view-to-view. Views handle the logic that takes place as you interact WITH a particular view. Things like events, but also things like the values and labels of things on the screen, and how those should change and react to the user.

**Comment by edubkendo** [comment]
Even better way of thinking about it: Controller's should handle the logic of how the user interacts with the data, views handle the logic of how the user interacts with the presentation.

**Comment by maedi** [comment]
Great, that makes sense. In a way Rails wasn't setup for the complex interactions within a page.

What are you thoughts on `views/templates`?

**Comment by edubkendo** [comment]
I don't have a strong feeling either way, but if others would be happier with it I would be fine with that. I think that was discussed at one point though I am not certain.

**Comment by maedi** [comment]
No worries, by the way this guide nicely explains the client/server differences:
http://emberjs.com/guides/ember_mvc/#toc_differences-from-ruby-on-rails

**Comment by onyxrev** [comment]
I've been following this conversation since trying to put something together with the new ember integration.  Some clarification on how the templates would be useful to produce server-generated HTML would be helpful.  

My main beef with this arrangement is purely the number of places one has to go to get something to render in the browser when one adds an action.  You need to modify the server controller, possibly the client controller, the routes, make a view, and make a template.  That's a lot of things!  This could potentially be alleviated by an action generator, but that doesn't solve the maintenance burden, just the initial burden of touching the files.

Is there any way for Tower to infer the Ember view from the template?  Each ember client view seems awfully boilerplate.  I'll admit I don't know a lot about Ember in particular, but I don't see those needing much customization.  So maybe we can apply some convention and do away with the client view files?

**Comment by lancejpollard** [comment]
@onyxrev I agree there is still a lot of boilerplate with the views, something we should definitely think about cleaning up.

FYI, the generated ember views aren't necessary (at least the blank views with just a `templateName` in them). They were just there to give you a starting point to add more functionality. Really, I think you can just render the views in the main layout HTML with a `data-template-name` attribute, the same way the application template is rendered, and Tower should create an Ember.View for you. Maybe it doesn't though, not sure, it should be a one-liner to add if not, just making this method more robust:
- [packages/tower-view/client/emberHelper.coffee#L26](https://github.com/viatropos/tower/blob/874573fac7d6c369c173b276bf2074655b03961e/packages/tower-view/client/emberHelper.coffee#L26)

@Maedi I'll mess around with the `views/templates` nesting to see how it feels. My first impression is that although it makes sense, it's combining two distinct sets of functionality, so that you'd have `views/templates` and `views/users`, etc., and/or it would break the convention of having `client` and `server` folders just below the app/\* folders. It feels similar to if you were to have `app/models/data` to put in your seed data, or `app/controllers/sockets` for socket handlers. Really I think all that stuff should go at the top level. More than anything though I think this is all just new territory so everything feels a little strange at first. That ember guide you linked is good.

**Comment by lancejpollard** [comment]
Just wanted to say, you guys probably have more experience than I do with the client views. I haven't had much time to spend on "apps" lately, but soon the docs will be updated and I'll have some time to really mess around with the `Ember.View`. It seems really powerful and a useful abstraction.

Until then, looking to you for examples! :)

**Comment by maedi** [comment]
I can't argue with your `client/server` logic, though in your example I think `views/users` would be `views/client/users`.

Yeah I feel familiar with the current folder setup already. Thinking through the typical user interaction workflow, the current structure is starting to make sense:

```
app
  |-- config         1. Initial configuration
  |-- controllers    2. The user requests a page
  |-- models         3. The controller responds with data from the model 
  |-- stylesheets
  |-- templates      4. Data is pushed into the views template
  |-- views          5. Views displays page and directs further requests to controller
```

Still a part of me says that templates are so closely related to views that they need to be children, _they are the same concept_ (the presentation), just different interfaces. The `data` and `sockets` directory are relatively different concepts compared to `models` and `controllers` respectively.

In the above example I had `templates` as the 4th step and `views` as the 5th, but really it is the other way round. The view outputs to the template. Contrasting this to `data/seeds` example where the seeds output to the model, not the model to the seeds.

Technically you could get away with:

```
views
  |-- client
    |-- layout
    |-- users
  |-- shared
    |-- templates
      |-- layout
      |-- users
```

or just:

```
views
  |-- client
    |-- layout
    |-- users
  |-- templates
    |-- layout
    |-- users
```

Just thinking aloud.
