### ISSUE TITLE
Running controller methods - Error! (Windows)

### ISSUE THREAD

**Issue by thehydroimpulse** [tower-archive/tower#316]
One step closer on getting Tower to run on Windows.

The problem is on line **56** in `packages/tower-controller/shared/instrumentation.coffee` and specifically the `try` and `catch` blocks. It appears that it's trying to locate the action `welcome` or `index` in this case within `@` but it doesn't exist and returns undefined. The `.call` then fails because it's passed an `undefined` value. The `@action` variable is working and outputs the correct string but the problem is within the `@[]`.

Any ideas?

**Comment by lancejpollard** [comment]
Try logging the object you're in:

``` coffeescript
    block = (callback) =>
      console.log @constructor.toString(), @
      try
        @[@action].call @, callback
      catch error
        callback(error)
```

Often if you get an error here saying the action isn't defined it's because it's calling it on ApplicationController for some reason (haven't fully solved that problem yet, but). The reason this is happening might be because it's [for some reason] not finding any matching routes, but the route `@root '/'` may match, but it still also parses the action (if this is the case we need to write tests to fix and resolve this more permanently. It has also happened because the coffee-script compilation didn't use the `./coffee-inheritance.js` code, so subclasses of `App.ApplicationController` may not be registering correctly and so `App.PostsController.toString()` might result in `"ApplicationController"` - I have seen that before.

Copy/paste the output of logging `this.constructor.toString()` and `this` from the code above into a gist and let me know, that may offer more info.

Another useful thing to do is `console.log(this.constructor.metadata())` and make sure that is correct.

Another thing to inspect is if the class is being defined multiple times. In the past - when working on automatically reloading code on the server when a file changed - reloading the file redefines the class, but there is some reference that's still around using the old code (this shouldn't be happening b/c all references classes, such as in the associations, are stored as strings until they're being called, but it still may). This might cause unexpected/random errors like this.

Oh, and since this is on windows, it's possible that the controllers (and others) aren't being loaded b/c of the windows/*nix `path` differences, so try inspecting `_.keys(App)` and see if everything that should be defined is.

Once we figure out why this is happening we should write tests to make it doesn't happen in the future because this is definitely an error that's difficult to debug.

**Comment by thehydroimpulse** [comment]
Ok so having:

``` coffee
console.log @constructor.toString, @ 
```

Returns: https://gist.github.com/3808368

``` coffee
console.log @constructor.metadata()
```

Returns: 

```
Processing by ApplicationController#index as HTML (GET)
  Parameters: { action: 'index', format: 'html' }
{ className: 'ApplicationController',
  resourceName: 'application',
  resourceType: 'Application',
  collectionName: 'application',
  params: {},
  renderers: {},
  mimes: { json: {}, html: {} },
  callbacks: {},
  helpers: [],
  belongsTo: [],
  subscriptions: [],
  layout: undefined,
  scopes: {},
  scopeNames: [] }
```

``` coffee
console.log _.keys(App)
```

Returns:

```
  Processing by ApplicationController#index as HTML (GET)
  Parameters: { action: 'index', format: 'html' }
[ 'app',
  'server',
  '__ember1349037332463_name',
  'io',
  'isStacked',
  'Post',
  'User',
  'ApplicationController',
  'PostsController',
  'UsersController' ]
```

**Comment by lancejpollard** [comment]
Yep that's it then, it's probably using ApplicationController when it should be using some subclass. What is the url you're accessing? And the route mapping that url to the controller action (or just paste your whole `routes.coffee`).

Is there an `index` action defined on your ApplicationController?

**Comment by thehydroimpulse** [comment]
My routes:

``` coffee
Tower.Route.draw -> 
  # @match '(/*path)', to: 'application#index' 
  @match '/', to: 'application#index' 
```

I had tried scaffolding other controllers but the output was the exact same. I also tried the `welcome` action vs the `index` action and it returned the same output. And yes there is an index method defined.

**Comment by lancejpollard** [comment]
If you copy/paste your code from

```
app/controllers/server/applicationController.coffee
```

to

```
app/controllers/client/applicationController.coffee
```

Then it will compile it to

```
./public/javascripts/app/controllers/client/applicationController.js
```

(This is just a hack to see the compiled output quickly, since only `client` files get compiled to `./public`). Once you do that, what does the code from that file look like?

```
./public/javascripts/app/controllers/client/applicationController.js
```

Since you do have a route pointing to `application#index` and the `index` method is defined, the only reason I can think of that it's not working is because the coffee-script isn't compiled correctly for Ember.

Given this:

``` coffeescript
class App.ApplicationController extends Tower.Controller
  index: ->
    @render 'index'
```

Plain-old CoffeeScript will generate this:

``` javascript
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

App.ApplicationController = (function(_super) {

  __extends(ApplicationController, _super);

  function ApplicationController() {
    return ApplicationController.__super__.constructor.apply(this, arguments);
  }

  ApplicationController.prototype.index = function() {
    return this.render('index');
  };

  return ApplicationController;

})(Tower.Controller);
```

But Tower's [./coffee-inheritance.js](https://github.com/viatropos/tower/blob/master/coffee-inheritance.js) extensions will generate this:

``` javascript
(function() {
  var __defineProperty = function(clazz, key, value) {
  if (typeof clazz.__defineProperty == 'function') return clazz.__defineProperty(key, value);
  return clazz.prototype[key] = value;
},
    __hasProp = {}.hasOwnProperty,
    __extends =   function(child, parent) {
    if (typeof parent.__extend == 'function') return parent.__extend(child);
    for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } 
    function ctor() { this.constructor = child; } 
    ctor.prototype = parent.prototype; 
    child.prototype = new ctor; 
    child.__super__ = parent.prototype; 
    if (typeof parent.extended == 'function') parent.extended(child); 
    return child; 
};

  App.ApplicationController = (function(_super) {
    var ApplicationController;

    function ApplicationController() {
      return ApplicationController.__super__.constructor.apply(this, arguments);
    }

    ApplicationController = __extends(ApplicationController, _super);

    __defineProperty(ApplicationController,  "index", function() {
      return this.render('index');
    });

    return ApplicationController;

  })(Tower.Controller);

}).call(this);
```

The main difference is that Tower customizes CoffeeScript to define instance methods like this:

``` javascript
__defineProperty(ApplicationController,  "index", function() {
  return this.render('index');
});
```

whereas plain CoffeeScript sets it on the prototype directly:

``` javascript
ApplicationController.prototype.index = function() {
  return this.render('index');
};
```

Core objects in Tower define that method ([packages/tower-support/shared/class.coffee#L17](https://github.com/viatropos/tower/blob/75a847de67edb83f80f6449232a7a8d61c867af2/packages/tower-support/shared/class.coffee#L17)) like this:

``` coffeescript
Tower.Controller.reopenClass
  __defineProperty: (key, value) ->
    object = {}
    object[key] = value
    @reopen(object)
```

So the controller is actually being defined like this:

``` coffeescript
class App.ApplicationController extends Tower.Controller
  @reopen
    index: ->
      @render 'index'
```

This is required so when you instantiate a new controller (or any core object in Tower), the instance gets the correct methods in the prototype/mixin/inheritance chain. Otherwise, Ember doesn't pass methods directly defined on the prototype to class instances, like this:

``` coffeescript
ApplicationController.prototype.index = function() {
  return this.render('index');
};
```

That could be the reason why the action is undefined in your case.

**Comment by thehydroimpulse** [comment]
Yup that fixes it! Thanks!

I just copied the contents of my server controller to the client and things ran as expected. There is just one small issue left in the watcher on windows... everytime you change a file the server will exit with an error stating: "
SyntaxError: Invalid regular expression: /\client\/: \ at end of pattern" but i'll take a look at it.

So it seems windows indeed works.

**Comment by lancejpollard** [comment]
Awesome! Yeah that second error is `tower-application/server/watcher.coffee` path issues...

So how did you fix the problem? It should be able to read the code from `server/applicationController.coffee`.

**Comment by thehydroimpulse** [comment]
Well so far I fixed the regular expression by changing it to: `@fileUpdated(path) unless path.match("\#{_path.sep}client\#{_path.sep}")` not sure if that will do it but it works for now.

I tried adding a `posts` resource generated by the scaffolding. It only has a `@scope 'all'` and a `destroy` method and it works. But trying the same thing within the `ApplicationController` on the client leads to more errors. It seems the application controller needs to have it's methods defined such as the bootstrap and `welcome` method identical to the server. Maybe it's not reading the server's version?

**Comment by thehydroimpulse** [comment]
Oh and a question... What's the benefit of changing coffeescript's way of achieving classes? 

Ok so I now I see why it's failing here. The coffeescript is being compiled but not properly. For some reason it's not wrapping a self invoking function around the rest of the compiled Javascript. Adding it manually fixes the whole problem. Not sure how this could be related to Windows as I've never experienced this on any other platform.

**Comment by lancejpollard** [comment]
The benefit is just being able to use the full range of coffee-script syntax (such as [executable class bodies](http://yehudakatz.com/2009/06/04/the-importance-of-executable-class-bodies/)), and because ember needs to have instance methods defined in `reopen`, and class methods defined in `reopenClass`; you can't define methods on an ember object using the prototype directly if you want to use computable properties or have it inherited in subclasses. So this won't work properly in ember:

``` coffeescript
App.User.prototype.welcome = ->
  # deliver welcome email
```

it must be done like this:

``` coffeescript
App.User.reopen({
  welcome: ->
})
```

So the extensions make it possible to use the simplicity of coffee-script in the API, while also being able to use ember.

**Comment by lancejpollard** [comment]
Can you paste the coffee-script that's getting generated? (So I can see what you mean by "it's not wrapping a self invoking function around the rest of the compiled javascript")

This may be happening b/c coffee-script may be working slightly different on windows (unlikely), or maybe the extensions are tied to *nix (also unlikely), or maybe the coffee-script grunt task isn't setting the right default options on windows. Not sure, post the code that's being generated and your version of coffee-script (local and global), that will help.

Thanks.

**Comment by thehydroimpulse** [comment]
``` coffee
class App.ApplicationController extends Tower.Controller 
    index: ->
        @render 'welcome'

```

Compiles to:

``` javascript
var __defineProperty = function(clazz, key, value) {
  if (typeof clazz.__defineProperty == 'function') return clazz.__defineProperty(key, value);
  return clazz.prototype[key] = value;
},
  __hasProp = {}.hasOwnProperty,
  __extends =   function(child, parent) {
    if (typeof parent.__extend == 'function') return parent.__extend(child);
    for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } 
    function ctor() { this.constructor = child; } 
    ctor.prototype = parent.prototype; 
    child.prototype = new ctor; 
    child.__super__ = parent.prototype; 
    if (typeof parent.extended == 'function') parent.extended(child); 
    return child; 
};

App.ApplicationController = (function(_super) {
  var ApplicationController;

  function ApplicationController() {
    return ApplicationController.__super__.constructor.apply(this, arguments);
  }

  ApplicationController = __extends(ApplicationController, _super);

  __defineProperty(ApplicationController,  "index", function() {
    return this.render('welcome');
  });

  return ApplicationController;

})(Tower.Controller);
```

when every other controller, for example the 'posts' controller compiles to:

``` javascript
(function() {
  var __defineProperty = function(clazz, key, value) {
  if (typeof clazz.__defineProperty == 'function') return clazz.__defineProperty(key, value);
  return clazz.prototype[key] = value;
},
    __hasProp = {}.hasOwnProperty,
    __extends =   function(child, parent) {
    if (typeof parent.__extend == 'function') return parent.__extend(child);
    for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } 
    function ctor() { this.constructor = child; } 
    ctor.prototype = parent.prototype; 
    child.prototype = new ctor; 
    child.__super__ = parent.prototype; 
    if (typeof parent.extended == 'function') parent.extended(child); 
    return child; 
};

  App.PostsController = (function(_super) {
    var PostsController;

    function PostsController() {
      return PostsController.__super__.constructor.apply(this, arguments);
    }

    PostsController = __extends(PostsController, _super);

    PostsController.scope('all');

    __defineProperty(PostsController,  "destroy", function() {
      return this.get('resource').destroy();
    });

    return PostsController;

  })(Tower.Controller);

}).call(this);

```

As you can see the `ApplicationController` doesn't have a wrapping:

``` javascript
(function(){

}).call(this);
```

Which would make sense why it's not working as it's not being called.

**Comment by lancejpollard** [comment]
Hmm... what is the difference between `postsController.coffee` and `applicationController.coffee` (what are their paths)?

Technically the `ApplicationController` code you posted above should still work since it will just execute straight through - it wouldn't work if it was wrapped like this:

``` javascript
(function(){

});
```

But since these errors are occurring for you on the client (not server) it probably does have to do w/ the fact that it's not wrapped because some variables may be being defined globally at that point.

What specific errors are you getting on the client?

**Comment by thehydroimpulse** [comment]
Error:

```
TypeError: undefined is not a function
    at Tower.ControllerInstrumentation.process.block (C:\Users\Daniel\Documents\tower_3\lib\tower-controller\shared\instrumentation.js:60:16)
    at Tower.SupportCallbacks.runCallbacks (C:\Users\Daniel\Documents\tower_3\lib\tower-support\shared\callbacks.js:71:15)
    at Tower.ControllerInstrumentation.process (C:\Users\Daniel\Documents\tower_3\lib\tower-controller\shared\instrumentation.js:71:17)
    at Tower.ControllerInstrumentation.call (C:\Users\Daniel\Documents\tower_3\lib\tower-controller\shared\instrumentation.js:47:17)
    at Function.Tower.NetRoute.NetRoute.reopenClass.findController (C:\Users\Daniel\Documents\tower_3\lib\tower-net\shared\route.js:99:20)
    at Function._.extend.find (C:\Users\Daniel\Documents\tower_3\lib\tower-middleware\server\router.js:20:27)
    at Function._.extend.render (C:\Users\Daniel\Documents\tower_3\lib\tower-middleware\server\router.js:23:28)
    at C:\Users\Daniel\Documents\tower_3\lib\tower-middleware\server\router.js:11:37
    at Tower.Application.Application.reopen._loadApp (C:\Users\Daniel\Documents\tower_3\lib\tower-application\server\application.js:348:16)
    at Object.Tower.MiddlewareRouter [as handle] (C:\Users\Daniel\Documents\tower_3\lib\tower-middleware\server\router.js:10:41)
```

Ok so I guess it's not the wrapping function but it seems that Tower is trying to load the client controller action instead of the servers. When I have a blank client `ApplicationController` it leads to the previous error. But when I mach the server controller's method `ApplicationController#welcome` and define it within the client it works without any errors. Also the coffeescript is being compiled correctly.

**Comment by thehydroimpulse** [comment]
**PostsController**

Server: **app/controllers/server/postsController.coffee**

``` coffee
class App.PostsController extends App.ApplicationController 
  @param 'title' 
  @param 'body' 

  @scope 'all' 

```

Client: **app/controllers/client/postsController.coffee**

``` coffee
class App.PostsController extends Tower.Controller 
  @scope 'all' 

  # @todo refactor 
  destroy: -> 
    @get('resource').destroy() 
```

**ApplicationController**

Server: **app/controllers/server/applicationController.coffee**

``` coffee
class App.ApplicationController extends Tower.Controller 
  @layout 'application' 

  @param 'page', type: 'Number', allowRange: false, allowNegative: false 
  @param 'limit', type: 'Number', allowRange: false, allowNegative: false 
  @param 'sort', type: 'Order' 
  @param 'fields', type: 'Array' 
  @param 'createdAt', type: 'Date' 
  @param 'updatedAt', type: 'Date' 

  @beforeAction 'bootstrap'#, only: 'welcome' 

  welcome: -> 
    @render 'welcome', locals: {@bootstrapData} 

  # Example of how you might bootstrap a one-page application. 
  bootstrap: (callback) -> 
    data = @bootstrapData = {} 

    # for every model you add, you can add it to the bootstrap 
    # dataset by using this async helper. 
    _.series [ 
      (next) => App.User.all (error, users) =>
        data.users = users
        next()
      (next) => App.Post.all (error, posts) =>
        data.posts = posts
        next()
    ], callback 
```

Client: **app/controllers/client/applicationController.coffee**

``` coffee
class App.ApplicationController extends Tower.Controller 
```

Oh and these are all generated resources. I haven't introduced custom code so that shouldn't be a problem.

**Comment by lancejpollard** [comment]
And your routes are like this (since you're switching to `welcome` action)?

``` coffeescript
Tower.Route.draw -> 
  @match '/', to: 'application#welcome' 
```

If the client controller is blank, then the error could be b/c the client routing implementation doesn't handle blank actions (not sure about this). By default the generated routes are in a `shared` folder so they are loaded on the client and server. If you want to have custom routes for the client vs. server, then you can move them to `app/config/client` and `app/config/server` instead of `app/config/shared`.

It seems that it's working now then?

**Comment by lancejpollard** [comment]
Been messing around with it for a bit on azure, it looks like it could be one of two things.

First, it could be an issue with how the `./coffee-inheritance.js` overrides are applied... By that I mean, when you `require('coffee-script')` in your app, and it's also required in the tower source, there could be two coffee-scripts installed:

```
./node_modules/coffee-script
./node_modules/tower/node_modules/coffee-script
```

I'm don't know 100% how the modules are resolved, but it seems like these are the rules:
- On installation, if the module is already installed at the parent level, it won't install it into it's own node_modules folder. So if you already have installed coffee-script in your app, then when you `npm install tower` in your app it won't install it's own coffee-script in `tower/node_modules/coffee-script`. Not sure if this is the case but it seems like it is.
- Then when you call `require('coffee-script')`, it will do a lookup up the chain, starting from the `__dirname` of the _current file_. So if you put `require('coffee-script')` inside `tower/lib/tower.js`, then it will lookup in tower's node_modules before your apps. Again, not sure about this but it seems the case. If you check `require.cache` you can see more about it.

So I was thinking it could be that we are applying the coffee-script extensions to a version of coffee-script installed in tower, but not the app. So I added coffee-script to tower's package.json so it got installed there, and removed it from the app, and made sure the only `require('coffee-script')` call was from `tower/index.js` in the tower source. But that didn't help. Still, there may be some issue with this.

The second thing is, it could be because Ember's run-loop isn't being called until later, so somehow the mixins aren't being added properly? I say that because of this:

``` coffeescript
# calling this in a generated app, from app/config/server/bootstrap.coffee at the top of the file
# none of the app/controllers/* code has been loaded by this point.
# getting the full path to the controller
controllerPath = require('path').join(Tower.root, 'app/controllers/server/applicationController.coffee')

loadOrReload = ->
  try require.resolve(controllerPath)
  delete require.cache[controllerPath]
  require(controllerPath)

seeIfExists = ->
  try
    console.log 'App.ApplicationController#welcome', App.ApplicationController.create().welcome
  catch error
    console.log 'App.ApplicationController#welcome', error

# it has never been loaded so this will fail
seeIfExists() #=> error

# attempt 1
# If you require it, you'll get App.ApplicationController,
# but the `welcome` method will be undefined.
# That is the error that you're getting
loadOrReload()
seeIfExists() #=> undefined

# attempt 2
# If I instead run this inside an `Ember.run` block,
# which forces ember to compile it's modules,
# then it seems to work:
Ember.run =>
  loadOrReload()
  seeIfExists() #=> [Function]
```

There could be some issue where the same file is being loaded twice because of some [more random] path issues on windows, such as maybe one version of applicationController is starting with `\\\\` and another with `C:\\\\`, so it's loaded twice.

Other than that, the last issue is making sure the template paths resolve correctly, which should be easier.

Hope that helps.

**Comment by lancejpollard** [comment]
So it looks like it could be as simple as both the client and server applicationController.coffee files are being loaded o_o:

``` javascript
// on azure
console.log(Object.keys(require.cache));
[
...
'\\\\10.207.104.177\\volume-22-default\\some-hash\\another-hash\\site\\wwwroot\\app\\controllers\\server\\applicationController.coffee'
...
'\\\\10.207.104.177\\volume-22-default\\some-hash\\another-hash\\site\\wwwroot\\app\\controllers\\client\\applicationController.coffee'
]
```

**Comment by lancejpollard** [comment]
http://tower-azure-test.azurewebsites.net/

**Comment by thehydroimpulse** [comment]
That makes a lot of sense as to why it didn't work before. I'll try it in a little bit...

**Comment by thehydroimpulse** [comment]
@viatropos Is the npm version up-to-date with github's?
