### ISSUE TITLE
Should I use it for production to build an api

### ISSUE THREAD

**Issue by panbhag** [tower-archive/tower#318]
Hi, 
We are building an application in nodejs. We are planning to use tower.
We don't need the view layer, we only need the routes, controllers and orm. We would be going to production in a months time.

My concerns

1) If we are only implmenting api, do you see it good to go to use for production.

2) We need good performance. Are there major performance issues at this point. If yes then in what layer.

3) We are keen on using the routes, controller section. We can use another ORM like mongoose, if the performance problem is in the orm or if its not production ready yet.

4) Extending it/ using third party module, would be similar to express, or would it be very different. 

We were evaluating raw express for the same, but there would be some extra work involved in that to implement rails like routing and controllers.

Please suggest.

Regards,
pankaj

**Comment by thehydroimpulse** [comment]
While Tower is not "production" status right now (there are still stuff missing and some optimizations. So 0.5 would be straight production mode?)
1. If your only implementing an api then you have a few options. Using tower is one of them.
   
   Honestly building an api in solid express would work. You would just need to abstract a routing system and combine an orm of your choice. 
   
   Tower would be the simpler choice as it already has the routing in place as well as really good data export (json, html, etc...)
2. I haven't done any benchmarks on Tower so I have nothing to compare it. But I don't see any immediate problems in terms of performance. I believe version 0.5 will have a tone of optimizations done.
3.  Again haven't done any benchmarking but the orm seems solid in Tower. There are no many-to-many direct relationships (last I checked) because of poor performance. Instead you use a third model to link two other models. This is just an example of a performance boost done to the orm using mongodb.
4. Extending Tower is fairly easy. Because Tower is built on express and connect your able to create your own middleware. In https://github.com/viatropos/tower/blob/master/test/example/app/config/server/bootstrap.coffee your able to define custom connect / express middleware.

If you need complete custom functionality that isn't built into Tower you can always modify Tower's source code and patch where needed. It may take a little while to learn how the system works and what does what, but after that you should be able to mod where needed.

Try building simple Tower apps or start the api in Tower. If you like the system and how things work then go for it, otherwise you can always fallback on express / connect.

**Comment by lancejpollard** [comment]
One more note, if you're building a startup and need to have your product out in like 3 weeks or something, then definitely use something more established like plain express. There's still a few edge cases to work out with the way requests are parsed in Tower before I'd say otherwise.

That said, everything is working and things are moving pretty fast, so if you're more talking 3 months, then definitely give it a shot. The server-side model and controller layers are the most robust part of Tower (and what I am working on finishing first), so we'll be tackling any issues that come up with "api" stuff first.

If you have any questions feel free to post issues or meet us in #towerjs IRC.

Good luck!

**Comment by panbhag** [comment]
Thanks for the info.  I think I would wait for tower to go into production. Till then I will go ahead with http://locomotivejs.org/.

Thanks,
Pankaj

**Comment by maedi** [comment]
I would argue that Tower is more feature complete and active than Locomotive. And does the client/server separation really well. But Locomotive looks fine, though it looks like a purely server side framework?

**Comment by panbhag** [comment]
Completely agree with you. I would love to use tower when its production
ready. At this point our needs are very less. Locomotive is lean, stable
and satisfies all our needs now. Thus decided to go ahead with the same.
Yup its completely server side. We already have an independent client side
implemented, so just need apis.I would wait for tower to go to production,
and would definitely consider it to use in the next release.

That said, I am really impressed by the responsiveness of the towerjs team.
The team is available all time, and I get responses in few minutes most of
the times!

Pankaj

**Comment by edubkendo** [comment]
@Maedi completely agree tower is definitely much more active and complete than locomotive. If I were going to use something for production right now, I'd simply build on express. As far as the purely server-side part, i think that is all @panbhag is looking for, when he said he just wanted to build an API. Again, though I'd go with express and either build my own ORM, use mongoose, or use tower and chip in to help bring it to 0.5.0 If you look at locomotivejs, it hasnt been updated in at least two months. There is http://flatironjs.org/ , which is being actively developed and is backed by nodejitsu, which I'd go with over locomotivejs. Not to knock locomotive, but if you are looking for production-ready frameworks, I'd assume support is a big deal. I would wager that tower is probably more capable of handling production than locomotive is, at this point. Versioning is, of course, somewhat relative, but locomotive is only at version 0.3.1 and has seemingly slowed or halted in development.

Edit: just saw it looks like you've already used locomotivejs. If that is the case and its working for you, then ignore my previous comments.

**Comment by thehydroimpulse** [comment]
@edubkendo Doing exactly what you pointed out. Contributing to Tower as much as I can so that I can use it to build some of my applications. Instead of rolling my own, or going with another framework (Rails), I would much rather contribute to a growing community.

**Comment by panbhag** [comment]
@edubkendo flatironjs look v good. but i feel it will have a learning curve. Locomotive is almost same as express with a structure added , plus rails like controllers and router. Being from Rails background, and with time crunch, thought it would be a better choice than express. So decided to move ahead with locomotive. Still I will give a shot to flatironjs as well. If I can start using it quickly, then I may use it. 

Thanks
