### ISSUE TITLE
lib directory has stuff left over from before client/server code was moved

### ISSUE THREAD

**Issue by chrixian** [tower-archive/tower#33]
when you moved some client and server code into their own directories there still exists some .js files that had their .coffee file moved. see assets.js vs assets.coffee or engine.js vs engine.coffee for example

also /src/tower/server/application.coffee line 183 `require './assets'` which ends up working because of the left over asset.js in /lib/tower/server but it was moved to './application/assets'

it would be nice if, things like /lib/tower/server/generator/generators/tower/app/templates were moved out of /lib and then lib could just be a compiled version of src

**Comment by lancejpollard** [comment]
Thanks for pointing that out, we need a better way of making sure the compiled files are removed when a coffeescript file is removed.

Agreed, putting the generators into `src` is the ideal solution, that just means updating the `Watchfile`.  Will do that soon.

**Comment by ludicast** [comment]
The awesome sockjs is written in coffeescript and does a compile-on-install (note the empty lib directory in their github).

https://github.com/sockjs/sockjs-node

I basically ripped that approach for my box.net libs (https://github.com/ludicast/node-box) and it works well.

I could do a demo of that for tower if you would consider this approach (which would avoid checking generated files into the repo).

**Comment by lancejpollard** [comment]
Hey that's a good idea.  There's a few things we should consider though.

First, there's also the build in coffee-script solution.  CoffeeScript automatically converts .coffee files when they are required with `require('x')`.  My concern here is I'd like to minimize the number of dependencies Tower has so as to minimize the size of the compiled slug in production.

The solution you just proposed is nice because it prevents having to deal with deleting old files and checking in compiled files.  I want to get rid of the compiled files in the GitHub repo anyway because it just adds to the repo size.  But, this introduces the potential of people not having the right version of coffee-script and so getting started with Tower might become a little more complicated.  If we can make this flawless, then I'm in.

**Comment by ludicast** [comment]
Yeah, I'll run with this over the next week or two (unless someone gets to it first).  In the makefile for sockjs they call coffee compiler like:

COFFEE:=./node_modules/.bin/coffee

so something like that should work well for tower.

**Comment by lancejpollard** [comment]
The lib directory has been added to `.gitignore` in the `development` branch.
