### ISSUE TITLE
should minify assets when bundling for production env

### ISSUE THREAD

**Issue by svasva** [tower-archive/tower#346]
This is how I monkeypatch my Cakefile for now:

```
# This bundles all of your assets into neat little files
task 'assets:bundle', ->
  invoke 'environment'
  Tower.ApplicationAssets.bundle(minify: (process.env.NODE_ENV is 'production'))
```

But that doesn't work as expected, having some trouble with minified variables:

```
Uncaught Error: Constant 'App.r' wasn't found
Uncaught Error: Constant 'App.n' wasn't found
```

**Comment by lancejpollard** [comment]
This is a bug that has to do with the coffee-script extensions in ./coffee-inheritance.js. We just need to change this (coffee-script output for an `App.Address` model):

``` javascript
App.Address = (function(_super) {
  // since this is being declared as a local variable, uglify.js will minify it,
  // making it App.r or some random shortened name, vs. App.Address.
  var Address;

  function Address() {
    return Address.__super__.constructor.apply(this, arguments);
  }

  Address = __extends(Address, _super);

  // ...

  return Address;

})(Tower.Model);
```

If you would like to fix this let me know, I'll do what I can to help. Won't be able to get to this for a bit (workaround at the bottom of this post).

One approach is to change this line:

``` javascript
Address = __extends(Address, _super);
```

to something like this:

``` javascript
Address = __extends('Address', _super);
```

That way it passes the string `'Address'` to `__extend`, and we can use that to set the class name. The way we're hooking into this is found here:

[packages/tower-support/shared/class.coffee#L8-12](https://github.com/viatropos/tower/blob/2376f81f1e37897f073db300a4d9d78b96a29572/packages/tower-support/shared/class.coffee#L8-12)

``` coffeescript
__extend: (child) ->
  object = Ember.Object.extend.apply @
  object.__name__ = child.name
  @extended.call(object) if @extended
  object
```

By passing a string instead of the result of `var Address` into that function, the `__extend` method above would just do this:

``` coffeescript
__extend: (name) ->
  object = Ember.Object.extend.apply @
  object.__name__ = name
  @extended.call(object) if @extended
  object
```

To make this change, we have to modify the [./coffee-inheritance.js](https://github.com/viatropos/tower/blob/master/coffee-inheritance.js) file so it passes a string, like above:

``` javascript
Address = __extends('Address', _super);
```

I haven't dug into the coffeescript compiler that hardcore so haven't been able to implement this. Would love help.

> Note: A temporary workaround is to set the `@__name__` property on your model, like this:

``` coffeescript
class App.Address extends Tower.Model
  @__name__: 'Address'
```

**Comment by edubkendo** [comment]
@viatropos arent we going to be moving away from the custom coffeescript compile stuff? should anyone be worrying about fixing that stuff or would it be better just to use temp. workarounds until we change the api?

**Comment by lancejpollard** [comment]
@edubkendo Ideally I'd think it would be useful to solve the custom coffee-script stuff (maybe using [CoffeeScriptRedux](https://github.com/michaelficarra/CoffeeScriptRedux) like you mentioned). If we can get it to work just as we originally desired (with custom overrides for `extends` for Ember, etc.) then if anyone who really loved CS and it's class declaration syntax used tower, they would be greeted with a super complete API.

I would like to support those things, but it would be purely just to round out the experience with the API for CS users. This kind of stuff will really just be extras to the API; everything will still default to JS/CS like you're saying.

So I personally probably wont work on this "CS API stuff" in the short term, but it's cool if anyone wants to make a pull request for this. I will still be working on the JS API (which will make updates to the CS api too).
