### ISSUE TITLE
vhost support?

### ISSUE THREAD

**Issue by norman784** [tower-archive/tower#354]
There is a way to support vhost on tower or just I need create separate apps to support multiple domains / subdomains?

**Comment by thehydroimpulse** [comment]
Are you just wanting an alias for multiple apps?

**Comment by norman784** [comment]
What I do is run a single application running daemon owner of domain / subdomain, I am not aware if recommended to do that or in separate processes (as in this case applications are interrelated) one would be the frontend / backend and server api.

For example:

api.mydomain.com -> api / tower app
developers.mydomain.com -> developers / tower app

**Comment by thehydroimpulse** [comment]
So you want to let's say run your api on a sub domain? That kind of thing?

**Comment by lancejpollard** [comment]
I haven't used vhosts much yet, but server-side Tower is built on Express, and they have a simple API for doing this:

http://stackoverflow.com/questions/5791260/how-can-i-configure-multiple-sub-domains-in-express-js-or-connect-js

In Tower you can access the "express" server via [`App.app`](https://github.com/viatropos/tower/blob/00c4527004b0015a228640467245ea8d929f87b0/packages/tower-application/server/application.coffee#L65) (and the http server itself via `App.server`, going to clean this api up in the future). You can add the vhost functionality in `app/config/server/bootstrap.coffee` for now, something like:

``` coffeescript
# app/config/server/bootstrap.coffee
App.configure ->
  # ...
  @use('vhost', 'm.mysite.com', require('/path/to/m').app)
  @use('vhost', 'sync.mysite.com', require('/path/to/sync').app)
  # ...
  @use Tower.MiddlewareRouter
```

The `@use` method just delegates to the express server:

[packages/tower-application/server/application.coffee#L114-L123](https://github.com/viatropos/tower/blob/00c4527004b0015a228640467245ea8d929f87b0/packages/tower-application/server/application.coffee#L114-L123)

If you want to manipulate the express server directly, you could do that like this:

``` coffeescript
App.configure ->
  express = @app # or App.server, same thing
  # ...
```

Let me know if you get vhosts running with this, would be nice to add to the wiki.

Is this what you're asking?

**Comment by norman784** [comment]
Yes, that is, then I've another question to get started (because i'm just today start with coffee-script and towerjs) I need to create an tower app with this configuration, then require other towers apps?

``` coffeescript
# vhost-app/config/server/bootstrap.coffee
App.configure ->
  # ...
  @use('vhost', 'm.mysite.com', require('/path/to/m/tower/app').app)
  @use('vhost', 'sync.mysite.com', require('/path/to/sync/tower/app').app)
  # ...
  @use Tower.MiddlewareRouter
```

Is that so? I would test this later, because I'm migrating my backend from express to towerjs now...

**Comment by lancejpollard** [comment]
Cool, so all of your sub-apps are going to be tower apps as well?

There might be a couple little issues with this to think through:
1. How the sub apps' client-side code gets loaded.
2. How the multiple `App` objects related to each other.

Question, do the sub apps run in a totally separate contexts/vm's, or are they all sharing the same global context?

If they're sharing the global context, then we may have to modify the `App` object, which is an `Ember.Application` object, which only allows one instance to be created. Let me know if this needs to be done. If not, then each sub-app would have it's own `App` object.

Also, the sub apps should export the `App`, which they aren't doing right now. That is defined in `app/config/shared/application.coffee`, so maybe changing it to this:

``` coffeescript
global.App = module.exports = Tower.Application.create()
```

If you did that, then your `require('/path/to/m/tower/app').app` would work.

I'll have to look more into sub-apps/vhosts, but if they can all share the same `App` instance, that would be ideal. Otherwise we'll have to discuss naming conventions and whatnot for the subapps, which might mean starting to implement something like [railties](https://www.engineyard.com/blog/2010/extending-rails-3-with-railties/) in Tower.

Thoughts?

**Comment by norman784** [comment]
Seems much like the way im handling now the vhosts on express, I would try this...

My apps are running on the same server and the same enviroment, just an normal LAMP server (using apache proxy).

There is a nice [express example](https://github.com/visionmedia/express/blob/master/examples/mvc/lib/boot.js) where I borrow the code adding the virtual host layer

**Comment by lancejpollard** [comment]
Awesome, thanks!
