### ISSUE TITLE
`cake assets:bundle` creates binary files

### ISSUE THREAD

**Issue by yusugomori** [tower-archive/tower#37]
I tried newly created project in production mode.

`cake assets:bundle` command creates assets files like:

application-3b7ad283554209fae20cbf0d50eb0f1a.js
 application-d41d8cd98f00b204e9800998ecf8427e.css

which turned out to be binary files. (And of course, an error occurs when opening a page in the browser.)

I think it's because this:

In
`./node_modules/tower/lib/server/application/assets.js, line 60`

``` javascript
return gzip(result, function(error, result) {
  fs.writeFileSync(digestPath, result);
  return next();
});
```

using gzip() returns binary files.
Alternatively, I changed this line just to:

``` javascript
// return gzip(result, function(error, result) {
  fs.writeFileSync(digestPath, result);
  return next();
// });
```

which works fine.
Does the error occur only in my PC?

**Comment by lancejpollard** [comment]
I am not sure how gzipping works on a PC, but that gzip method will output a gzip encoded file.  I think the issue is that gzip headers aren't served correctly from the node server locally.  If you push those assets to S3 though, Amazon will recognize they're `application/x-gzip` and they'll be decoded to the javascript/css files.

We want the gzipping in there, need to make sure the HTTP headers for gzipping are set correctly on the node server though.

**Comment by yusugomori** [comment]
Ah, got it. I mistook the code.

So, just using node server with

`$ node server.js -e production`

can't fix the problem (still trying to find a way to serve application/x-gzip),

but using nginx, or I can say setting nginx.conf, will fix it.
