### ISSUE TITLE
When will be the version 0.5 released?

### ISSUE THREAD

**Issue by haohello** [tower-archive/tower#379]
I've found it has been developed for really a long time..

**Comment by lancejpollard** [comment]
We're refactoring/developing and preparing for a new release soon, may be a month or so. A lot of new stuff in the works.

**Comment by haohello** [comment]
I'm curious to know how many guys are now developing tower.js? And do you have any plans to set up a foundation to back up the tower.js development? You know currently the development is rather slow and it'll eventually diminish everyone's confidence for the future of the project.

**Comment by thehydroimpulse** [comment]
Lance (@viatropos) and I. I don't know any plans on getting a foundation up, but I'm definitely staying for the long haul. Once we hit 0.5 we'll be a lot more visible as were trying to keep things quite a little bit. You can check my fork https://github.com/TheHydroImpulse/tower were I do most of my work, though, I typically work locally then only push when things work. You can also check out the gist account of both Lance and I, that's where we put some of our ideas.

**Comment by btbinhtran** [comment]
I agree with haohello. There needs to be a foundation where new developers are feeling empowered by the momentum of the project to keep watching the project. Our foundation would be the main site.

The least we can do right now is to update the main site.
Repository located https://github.com/viatropos/towerjs.org

I'm willing to do that.

Let's discuss what updates to do on the main site that will have an immediate impact.

First, we can improve the site SEO. We're not even getting on the first page of Google results for "tower".

Second, we can brand ourselves better with a larger Tower image.

**Comment by lancejpollard** [comment]
In this for the long haul as well.

I definitely agree with you guys @btbinhtran and @haohello. There needs to be a foundation set up, been considering ways of doing this. When @TheHydroImpulse and I (and anyone else interested) get the new stuff merged for release, considering moving this repo to `github.com/tower/tower` (same with `/tower/towerjs.org`) and starting to have things revolve around that (similar to [jQuery](https://github.com/jquery/jquery), [Ember](https://github.com/emberjs/ember.js/), [Rails](https://github.com/rails/rails), etc.).

@btbinhtran If you would like to take lead on creating a new site that would be awesome and I'll be here to help whenever you need it (we can connect through email/skype as well). What are you planning with the main site in regards to having an immediate impact?

I am all about improving SEO if you have any suggestions, haven't done anything in this area.

Having someone focused on branding would be very helpful as well. I am not a designer but love high quality design. The major things we can do to improve the website in terms of branding are:
- creating a logo (I literally just grabbed this: http://thenounproject.com/noun/eiffel-tower/#icon-No891).
- creating a color scheme (back then I loved the look of http://www.dangersoffracking.com/, which is where the colors come from, but I have no opinion on the best color scheme right now).
- creating a responsive layout (that's optimized/fast, such as http://responsejs.com/)

The main site should just render GitHub flavored markdown, but down the road we can possibly customize this so we can add more interactive elements (such as a repl like http://try.redis.io/ or http://repl.it/languages/JavaScript, or d3 graphics/dashboards such as http://square.github.com/cubism/ since there will be docs showing how to create real-time dashboards). So in terms of improving the site now, the theme/design can be developed independently from the content, and integrating a new design would have an immediate impact. To get this out like tomorrow, it's fine with me if you even just start with the Ember website and change the look and feel, that would get us moving (https://github.com/emberjs/website).

If anyone has anything in particular they would like to help out on definitely let us know. If you'd rather discuss it over email or something else, don't hesitate to email me :)

**Comment by btbinhtran** [comment]
Following the Ember design is a great idea. It gives us a similar theme for people to relate Tower with Ember.

The first few things that I plan to do:
- Add an original logo
- An API section
- A guide section
- A quick flash-bang tutorial guide
- A more in-depth guide **Towerjs Tutorial**
- Orient theme towards a Tower that goes "high in the sky"

Also, having a weekly or biweekly posting of updates onto a blog or any social platform would help gain and maintain interest in Tower. I'm also still trying to write the **Towerjs Tutorial**.

I'll get things rolling on Monday. Enjoy your Superbowl weekend.

**Comment by thehydroimpulse** [comment]
Well, I'm Canadian, so we aren't really fans of the Superbowl, lol.

Anyways, I plan on updating my blog with weekly or bi-weekly (This can mean either every two weeks, or twice a week - some people get confused) with Tower news - http://hydrocodedesign.com

We got a lot of awesome stuff being worked on. You can view some of the new APIs on gist.github.com under @viatropos or myself.

If you have any suggestions, requests, etc.. Just let me know.

**Comment by maedi** [comment]
Great stuff @btbinhtran!

**Comment by lumin3000** [comment]
HI viatropos, just want you know that my web still working good in production (tower version 0.3.9-7).
i got user auth, shopping stuff, blog posts on the site. 
Thousands PV each day.
everything is light but stable. 
tower is realy a potential one. 
Cant wait to see the 0.5 birth.
