### ISSUE TITLE
encodeDate is broken for MongoDB seriazliation

### ISSUE THREAD

**Issue by stereosteve** [tower-archive/tower#38]
```
Tower.Store.MongoDB.Serialization.encodeDate("1/1/2011")
```

Moment.js does not define parse() or local().  Probably want to pass value directly to moment(val) constructor.

**Comment by lancejpollard** [comment]
Thanks for posting, need to finalize this.

The way the dates are going to work in Tower is like this: when you set an attribute on a model, it uses the `field` definition to convert the value to the actual date object right when it's set.  And [todo] when you do `updateAttributes`, it will do this as well.  This isn't complete with dates, it only works if given actual `Date` objects.  Then when you save the model to the database, the `Tower.Store` implementation will convert the `Date` value to the database-specific value (the database might only store the data up to the second rather than the millisecond, or needs to convert to some normalized timezone, etc.).

With that implementation, the example you posted is invalid:

``` coffeescript
Tower.Store.MongoDB.Serialization.encodeDate("1/1/2011")
```

The goal of the `Tower.Store` implementations is to take a very normalized and explicit set of parameters to minimize computation.  That's why the [`Tower.Scope` finder/persistence methods take dynamic arguments](https://github.com/viatropos/tower/blob/e0b61296ff6e25edd2ac01610dc9f647a67e1e74/src/tower/model/scope/persistence.coffee#L20), while the [`Tower.Store` takes explicit arguments](https://github.com/viatropos/tower/blob/13737b9ff2033fc3535b94eb0ff80814b8f58b4e/src/tower/server/store/mongodb/persistence.coffee#L2).  This way you can use the `Tower.Store` to get more low-level control (while still taking advantage of some helpful conventions), but since most people won't need to do that early on, if you _do_ use those methods directly you have to pass explicit args.

So, `Tower.Store.MongoDB#encodeDate` will only accept `Date` objects.

This is still an issue though, I'll get this fixed this week.  Thanks for bringing it up.

**Comment by stereosteve** [comment]
Gotcha.  I just started using Tower yesterday.  I ran the scaffold generator with a date type and got this error because the controller passes the String directly thru to the encodeDate function.

Also I was confused by this block.  Took me a minute to realize the Date and Array cases will never be matched because typeof returns a string.

```
switch typeof(value)
  time = require('moment')
  when "string"
    time.parse(value)
  when Date
    time.local(value.year, value.month, value.day, value.hour, value.min, value.sec)
  when Array
    time.local(value)
  else
    value
```

For now I'll parse the Date at the controller level and close this issue.

Anyways, Tower looks pretty awesome so far - lots of nice features.  Keep up the good work!

Steve
