### ISSUE TITLE
Guides section on the site, Layouts, returns error on compile

### ISSUE THREAD

**Issue by pocesar** [tower-archive/tower#393]
On Firefox 19.0.2, compiling the layout written in Coffeecup, is giving an exception:

```
SyntaxError: reserved word "yield" on line 25
```

`yield` is a reserved keyword on Javascript 1.7 and should be changed for future-proof support out of the box

**Comment by lancejpollard** [comment]
Try 'yields'

**Comment by pocesar** [comment]
that fixed it. so there's a typo in http://towerjs.org/guides showing `yield "templates"`

**Comment by edubkendo** [comment]
That site, and those guides, are horribly outdated and I believe they are soon to be replaced.

The most current docs are here: https://github.com/viatropos/tower/wiki

I have written a Tower tutorial here: http://nodehed.com/?p=15

@btbinhtran has a Tower guide available as a [PDF here](https://github.com/btbinhtran/towerjs-tutorial/blob/master/release/book.pdf?raw=true) and located at this repo: https://github.com/btbinhtran/towerjs-tutorial

Any of these may be out of date in parts because Tower v0.5 is due out very soon now, and will radically change the API from what I understand (simplified and awesome-ized), so I know that I, for one, and probably others too, have not been putting a lot of effort into updating soon to be obsolete documentation. If you need Tower now, feel free to use the current version. But my recommendation would be to spend the time learning [Ember](http://emberjs.com/) really well, as Tower is built on Ember from top to bottom, and by getting a good grip on Ember now will put you in the best position for learning Tower when it emerges. Hopefully really soon, eh @viatropos ? @TheHydroImpulse ?

**Comment by btbinhtran** [comment]
I agree with @edubkendo about getting a good grip on Ember. A really good resource is https://peepcode.com/products/emberjs

Once Tower v0.5 is out, the guides, docs, and the Towerjs Tutorial will be updated.

Also, @viatropos and @TheHydroImpulse are working as fast as they can to get the 0.5 release out the door.
In the future, merge requests will be processed faster because we will have more contributors having merge request authorization.
