### ISSUE TITLE
Embeddable documents in models

### ISSUE THREAD

**Issue by whatyoubendoing** [tower-archive/tower#4]
How bout you include some way to have embeddable documents in the models similar to how mongo mapper does it eg http://mongomapper.com/documentation/embedded-document.html.

**Comment by lancejpollard** [comment]
Still thinking which of these three ways is best:

#### 1. `@belongsTo "user", embed: true`

I'm leaning toward this one because it's the least amount of code and the most flexible.  But it is a little abstract so I'm also thinking # 3.

``` coffeescript
class App.User extends Tower.Model
  @hasMany "addresses", embed: true

class App.Address extends Tower.Model
  @belongsTo "user", embed: true
```

From a client perspective, I don't think you really need `embed: true` necessarily (haven't thought about this in depth though).  And for SQL, you wouldn't embed the documents into a column or whatever, the option would be ignored (future SQL adapters).  You only really need this for MongoDB and probably other document databases.

So, having the minimal amount of code would I think make it less confusing while still giving you the full power of embedded documents in MongoDB.

The second thing is that this is the most flexible.  Meaning what if you want to embed the `Address` in `User` documents in MongoDB for performance reasons, but you have a list of locations for not only users, but groups, events, products, etc.  Maybe you want to store the rest of the addresses in their own documents.  By having the `embed: true` option on an association, you handle both these cases:

``` coffeescript
user.addresses = [new App.Address]
user.save()
# user document:
# { _id: 'userId', addresses: [ {_id: 'addressId' ... } ] }
group.addresses = [new App.Address]
group.save()
# group document
# { _id: 'groupId' }
# address document
# { _id: 'addressId', addressibleId: 'groupId' }
```

#### 2. `@embeddedIn "user"`

This one wouldn't allow you to handle both cases.  It's basically saying "you have to embed this model in this document".  At least that's what it reads to me.

``` coffeescript
class App.User extends Tower.Model
  @embedsMany "addresses"

class App.Address extends Tower.Model
  @embeddedIn "user"
```

The other thing is this adds a few methods to the class that are specific only to document databases.  I'd rather avoid that.

#### 3. `@include EmbeddedDocument`

This is what you're saying with MongoMapper.

``` coffeescript
class App.User extends Tower.Model
  @hasMany "addresses"

class App.Address extends Tower.Model
  @include EmbeddedDocument
```

This one is more flexible than # 2, so it can be embedded in many different types of records, but you could do this with # 2 by creating a polymorphic association.

It's cleaner than both the other two, but I'm not sure if you always want to force a model to be embedded, that's the main thing I still want to get clear.

But yeah, this will be in there soon.

**Comment by benatkin** [comment]
I noticed that GitHub picked up your numbers as issue references. Perhaps prefixing them with a \ will work, like #2.

Edit: nope. :/
