### ISSUE TITLE
What! I even can't init a project

### ISSUE THREAD

**Issue by tamvm** [tower-archive/tower#407]
Hi, 

I'm new to nodejs and tower as well and just do some experimental with towerjs. But it looks that not be nice to me. After installing towerjs, I init a project by this command: 
`tower new sample`
but immediately it raised exception :( 

```
/usr/local/lib/node_modules/tower/node_modules/tower-cookbook/index.js:59
    return fn(new Error('Cookbook [' + name + '] not found.'));
           ^
TypeError: undefined is not a function
    at Object.exports.exec (/usr/local/lib/node_modules/tower/node_modules/tower-cookbook/index.js:59:12)
    at Object.exports.init (/usr/local/lib/node_modules/tower/bin/tower:191:6)
    at Object.exports.run (/usr/local/lib/node_modules/tower/bin/tower:117:26)
    at Object.<anonymous> (/usr/local/lib/node_modules/tower/bin/tower:333:46)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
```

**Comment by kbups** [comment]
Hello,

I have the same error. Do you find a solution?

Thanks in advance.

**Comment by tamvm** [comment]
I don't play with tower anymore :(

**Comment by eleung** [comment]
Tower is a lost cause, the unresponsiveness of there devs, and total lack of support is ridiculous. Ended up going with Derby.js and have no regrets.  

Edmond Leung

**Comment by thehydroimpulse** [comment]
@tamvo @kbups @eleung Tower is not ready to be used right now. Many of the components are still being developed.

**Comment by tamvm** [comment]
Really? Great! We will get back when it's really :+1: and try to contribute if I can.

**Comment by kristianmandrup** [comment]
Unfortunately.... most frameworks die a slow death :( I think the best we can do sometimes, is to salvage the best pieces and start up something new combining the best approaches from multiple frameworks etc.
It is very hard to sustain the motivation for huge projects like this unless you have a lot of community support, but most users are just leechers and not contributors. Such is the fact of open source. Coz large projects take a huge effort to really dig into and contribute to in most cases... I think the whole idea of trying to design frameworks to cover the whole spectrum are doomed to fail in the end, unless you got huge corporate backing to boot like Google etc.
Better to have smaller, self contained, specialize frameworks and them combine them as you like IMO
Which as the philosophy of this (and many other frameworks) but which is rarely "really" achieved...

**Comment by lancejpollard** [comment]
@kristianmandrup definitely agree with your points. Large monolithic projects take too much effort for the vast majority of developers to contribute to. When tower was one monolithic repo I personally felt like I reached a point where I could not keep it all in my head. I felt like I reached a wall where it was too much effort to go further. But then we switched to using components and it opened up a whole new set of possibilities. Now it feels like there is no mental limit that can be reached. Since every component is highly specialized and self contained, when you code a specific module, you only have to keep that in memory. Once that's done, you can combine that as part of a higher-level component, and mentally it feels no more demanding than building the part. We have been able to move much faster using this approach. We have to continue tinkering to find ways to isolate and specialize each component, but we are getting close to a simple solution.

It seems corporate backing like Google provides the ability to slowly chip away at monolithic projects b/c they have dozens if not hundreds of developers working on it. But this doesn't mean that's what it takes to build something in that arena. It just means we need to take a different approach, come at it from a new angle. Newcomers always have the opportunity to make something way more valuable than the existing large corporations, even if it's just one or two individuals.

Also wanted to say that while it may seem like there is a lack of motivation b/c of the lack of visibility/movement on the main tower repo, @TheHydroImpulse and I are working full time at startups and slowly finding ways to abstract away what we're doing into reusable components that come together into a unified framework. Doesn't matter how long it takes or if we go down a road that turns out a failure and we have to try again. Even though some people like piecing together the perfect parts (I often prefer that as well), having a unified framework will make it much easier for the vast majority of developers to make awesome stuff without having to think super hard about the details or stay on the edge of open source. It's like building a computer from the parts vs. buying a Mac. The Mac just makes it so much simpler to work with for the majority of users.

**Comment by kristianmandrup** [comment]
Wow! Great to hear that you are beginning to have it divided into many more smaller parts. I made the same realization a few times by now, when I also hit the wall with too big projects that I could no longer mentally manage.
When even the author of a project can no longer cope with the size of the project, it definitely is a warning that it is time to split it up into smaller, self-contained modules that can be managed individually. I agree, that size doesn't matter, which Microsoft proved again and again... hehe
In the end it is about the right ideas and clever designs. I think a lot could be simplified by going "all in" with a socket/real time updates approach, which is more similar to desktop apps, and only use the REST part to interface with other systems (data API). For the REST part, a Rails like MVC system makes sense, but for the User Application part I think we need a radically different approach more like Angular with Firebase or Meteor etc.
Bonne chance! I wish you guys all the best :)
