### ISSUE TITLE
Tower.assets is undefined

### ISSUE THREAD

**Issue by buhrmi** [tower-archive/tower#6]
Hi there,

I have problems getting started. Tower.assets is always undefined, so no assets are ever compiled and put into the public folder.

What could be the reason for this? It's a freshly generated app.

**Comment by buhrmi** [comment]
Is there a command I have to invoke to have the assets put into the public folder? cake assets:bundle will crash with Tower.assets being undefined.

**Comment by lancejpollard** [comment]
Yeah two things.

#### `cake assets:bundle`

You only need to run this when you're pushing your app to production.  It'll minify and gzip your assets into `public/assets`.  It takes a few seconds to run because the js/css compressors have to do their work.

I need to push the updates to this code (changed the api from `Tower.assets` to `Tower.config.assets` in the development branch).  But you don't need this for local development so you should be able to get through tonight with the next step: design.io.

#### `design.io`

The asset part of Tower works by using [design.io](https://github.com/viatropos/design.io) to compile assets whenever you save a file (or you start the design.io watcher).  There's a screencast on the readme.

[Technically, you can also just put assets directly into `public/x`, everything in there is read as a static file.  But you don't need to worry about that with design.io.]

Anytime you change a JavaScript or CoffeeScript file, it will compile them into `public/javascripts/[path].js`, and same with Stylus, LESS, or CSS, it will compile them to `public/stylesheets.css`.

So when developing an app, you have your node server, and you have your file watcher process using design.io - 2 terminal windows.  Going to make a screencast on how to build a basic tower app with design.io in the next week or so.

To start design.io, here's all you do:

```
npm install -g design.io
design.io start # starts an http server to inject stylesheets into the browser! more on this later in the week.
```

Then inside your project directory, run the design.io watcher:

```
design.io
```

Design.io's not perfect yet, but it's getting there.  It's very close in scope to [guard for ruby](https://github.com/guard/guard).  Hope that gets you started.  I'll be around tomorrow and I'll check back.

**Comment by buhrmi** [comment]
Thanks for the response!

I've done some troubleshooting too. As it turns out, design.io in it's current state won't watch anything unless it's installed locally without -g.

The offender is in `command.js:45`, appending `/node_modules/design.io/lib/design.io/command/watch.js` to the process dir, which is my project root.

I also had to install async, pathfinder, mint, less, javascripts and stylesheets extension manually.

Looks as if it's working now.

**Comment by buhrmi** [comment]
All right, heading home now.

Things I did not get to work were:
- Code Change reloading (had to restart server after each template/partial/controller/etc. change)
- Instant Browser refreshes. Websocket was connected, design.io watcher was busy recompiling CSS and templates in the other window, but did not send anything.

**Comment by moodyallen** [comment]
Hey guys,

I'm having the same issues with design.io

With <code>node server.js</code>
I am getting errors cos the app is on :3000 (default) and socket.io is watching :4181

With <code>tower server -p 4181</code> everything seams to be fine, but still got no sweet instant refreshes

**Comment by lancejpollard** [comment]
That shouldn't happen (linking to two different ports), but for reference that's happening because design.io needs to have the global http server running (`design.io start`) to inject the assets into the browser.  This process will all be managed transparently in the next commit so don't worry too much about it.  Working on a commit for this now, along with the instant refreshes.

**Comment by lancejpollard** [comment]
Closing this issue since it was originally about `Tower.assets` being undefined and that's fixed.  If you're still having issues with design.io let me know.
