### ISSUE TITLE
model relationships generate form fields?

### ISSUE THREAD

**Issue by jamespeerless** [tower-archive/tower#70]
Shouldn't defining model relationships such as belongsTo and hasMany during scaffolding generate form fields for specifying these attributes?

For example say I had the schema:

User email:string belongsTo:group
Group name:string hasMany:users

In my admin panel I would create some groups and then in the new user form I'd expect a select input that would let me pick between the available groups they could 'belongTo.'

**Comment by jamespeerless** [comment]
Also - do I need to explicitly define foreignKey fields in my schema or does defining the relationship handle that?

**Comment by lancejpollard** [comment]
Definitely been thinking about this.  I was never a big fan of how Rails used the select box for this kind of thing because it only works on the `belongsTo` side (you can say a comment belongsTo a post, and so select the post from the comment form, but what if I wanted to create a bunch of comments from the post form).  The reason is because in a real app there could be thousands of posts the comment can belong to so the select box gets unwieldy.

Another approach is to define it as a nested resource, so the comment form would be at `/posts/:postId/comments/new` and you don't need a select box.  I think the generator should somehow handle this case because it sets your app up more like it should appear in the real world.  Also, if there were 100's of posts to apply a comment to, then you would have to make a DB query and instantiate models on page load, and I'd like to avoid that if possible.

But then what if `comment` belongsTo `user` as well...  Then you should be able to select a user for the comment when you're at `/posts/:postId/comments/new`.  Hmm...  I think having some sort of autocomplete thing built in might be a useful solution (an autocomplete that doesn't require a whole jQuery library, something simple).

Let's think about what would set your app up to be most ready for the real world without requiring a ton of extra code (like a full-fledged autocomplete plugin).

> Also - do I need to explicitly define foreignKey fields in my schema or does defining the relationship handle that?

You can define foreign keys explicitly, but it will pick a default for you.

``` coffeescript
class App.Post extends Tower.Model
  @belongsTo "user", foreignKey: "adminId" # defaults to userId
```

There aren't robust tests for custom foreign keys though just realized, need to add that.

**Comment by jamespeerless** [comment]
Thanks for the quick response.  I guess the use case I was considering was for scaffolding out an admin panel.  I may want to add a bunch of categories, groups, etc things that other models would belongTo.  When adding things manually via an admin panel it just makes sense to be able to select what it belongsTo in a select box.  Autocomplete idea sounds interesting too. I agree this use case isn't one that would appear in a user-facing ui that often.  

I was going to try to add a form helper for doing this but I'd need to be able to reference the Model the resource belongsTo so I could use Model.All to retrieve all the possible models to pick from.  I just started looking at your source today, could you point me in the right direction?

**Comment by lancejpollard** [comment]
You can get the model class from the relation like this:

Here's some code showing how relations work:

``` coffeescript
class App.User extends Tower.Model
  @hasMany "posts"

class App.Post extends Tower.Model
  @belongsTo "user"

relations = post.constructor.relations() # App.Post.relations()
#=> {user: Tower.Model.Relation.BelongsTo}

belongsToRelations  = []
hasManyRelations    = []

for name, relation of relations
  if relation instanceof Tower.Model.Relation.BelongsTo
    belongsToRelations(relation)
  else if relation instanceof Tower.Model.Relation.HasMany
    hasManyRelations.push(relation)

userRelation = belongsToRelations[0]
userRelation.name           # "user"
userRelation.foreignKey     # "userId"
userRelation.klass()        # App.Post
userRelation.targetKlass()  # App.User
```

Hope that helps.  Note, this "internal" API for relations might change, I don't quite like `targetKlass` and such yet, need to find something better.

**Comment by tomchentw** [comment]
Just a little suggestion: @viatropos maybe u'll like what rails_admin do?
https://github.com/sferik/rails_admin
heres the demo site
http://rails-admin-tb.herokuapp.com/admin/team/new
a searchable dropdown for belongsTo
a two column widget for hasMany
