### ISSUE TITLE
Consider using "rel" library for generating queries

### ISSUE THREAD

**Issue by contentfree** [tower-archive/tower#79]
The strange $ syntax for querying in Tower is a fairly major hurdle for our team's adoption. It looks foreign and I can't decipher the reasoning behind it. Having a long history in Rails, we've all grown to love Arel. There's a port for Node called Rel – https://github.com/carlwoodward/rel. Please consider replacing the syntax the $ syntax with Rel (or something that builds on Rel).

**Comment by kristianmandrup** [comment]
I think that the $ syntax is part of mongoose which is using the native Mongo DB query. Mongoid and other Mongo-Rails mappers provide a layer on top of this query syntax to make it more AR-like. Mongo DB is not a relational DB, and so I don't think rel would work.

If this syntax is a hurdle, consider wrapping the Mongo advanced query API and make it a Tower plugin/extension. Just my take on it. I did this for the Geo parts of MongoDB that became a Mongoid extension (mongoid_spatial gem).

http://www.mongodb.org/display/DOCS/Querying

http://www.mongodb.org/display/DOCS/Advanced+Queries

**Comment by lancejpollard** [comment]
Correct, the `$` syntax is from the MongoDB Query API.  Tower's using that because it was an already elaborate and tested query language that handled a lot of cases.

I have not seen Rel before, looks interesting!  I loved Arel.  However, in Rails, I rarely used Arel directly as it was too verbose and difficult to understand, and I ended up using libraries like [Squeel](https://github.com/ernie/squeel).  I'm a fan of being able to read the syntax quickly.

Also, you can use `<= < > >=` and others instead of the `$` equivalent.  Check out the map:

[https://github.com/viatropos/tower/tree/master/src/tower/store.coffee#L25](https://github.com/viatropos/tower/blob/fe81c50885b404f9e2e4c9597f20950b0684fab8/src/tower/store.coffee#L25)

Here's a quick comparison (after scanning the Rel readme):

``` coffeescript
users.where(users.column('name').eq('bob'), users.column('age').lt(25))
users.where(name: 'bob', age: "$lt": 25)
users.where(name: 'bob', age: "<": 25)

users.where(users.column('name').eq('amy')).project(users.column('id'))
users.where(name: 'amy').select('id')
```

Tower's syntax is much cleaner.

Like @kristianmandrup said, try making this into a module for Tower, providing the alternate syntax.  I'll still think about this, but seeing some examples would help.
