### ISSUE TITLE
everyauth and .coffee view

### ISSUE THREAD

**Issue by sunyx** [tower-archive/tower#85]
I get an error when I try to use everyauth (password) with towerjs. The error lies in the login.coffee. An idea?
Thanks.
# Error

Error: Cannot find module 'coffee'
    at Function._resolveFilename (module.js:332:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
# application.coffee

https://gist.github.com/2360161
# authentification.coffee

https://gist.github.com/2360145

**Comment by lancejpollard** [comment]
I have no idea.  Can you print me the error stack trace?

It may from the way everyauth is determining node modules from the file extension, maybe you have to define a renderer for it...

**Comment by hadesgames** [comment]
I have run in to the same problem. 
The problem seems to be that `everyauth.password` wants to render the login view (and there is no way to overide this)

So everyauth renders the view directly without passing through tower. The `.coffee` files that tower uses are actualy `.coffeekup` files and thus there is no engine installed to render `.coffee` files

I though of two solutions for this problem:
1. Rename your login views from `.coffee` to `.coffeekup`. This worked for me but the files had to be in `/views` forlder not `/app/views`. One workaround for this is to have the path to the files something  like `../app/views/login.coffeekup`
2. Overload the `displayLogin` function which is the actual funtion that calls the rendering. The problem here is that I wasn't able to find out how to render a view, with tower, outside of a Controller. Some documentation for this would be extremely useful.

**Comment by marcinrogacki** [comment]
I done something like this to force .coffee extension:

``` coffeescript
# config/application.coffee

everyauth = require "everyauth"
coffeekup = require "tower/node_modules/coffeekup"

class App extends Tower.Application    
  @configure ->
    ...snip...
    @server.set 'views', './app/views' # everyauth use this path
    @server.register ".coffee", coffeekup.adapters.express # register engine with given extension 
    @server.set "view engine", 'coffeekup' # view engine for everyauth
    everyauth.helpExpress @server  # register view helper in express
    @use everyauth.middleware()
    @use Tower.Middleware.Router

module.exports = global.App = new App
```

But as hadesgames said, everyauth renders the view directly without passing through tower, giving another issue:

```
Error: failed to locate view "layout"
```

I can add next configuration line:

```
@server.set "view options", { layout: Tower.publicPath + "/../app/views/layouts/application.coffee" }
```

and the next issue:

```
TemplateError: Error rendering /home/marcin/Pulpit/towerApp/public/../app/views/layouts/application.coffee: failed to locate view "shared/meta"
```

So it looks pointless, cuz it's going to creating separate view engine.
